// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudWorkstationsV1
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc

func sample(
  client: WorkstationsClient, projectId: String, locationId: String, workstationClusterId: String
) async throws {
  let items = try client.listUsableWorkstationConfigs(
    byItem: ListUsableWorkstationConfigsRequest()
      .with {
        $0.parent =
          "projects/\(projectId)/locations/\(locationId)/workstationClusters/\(workstationClusterId)"
      }
  )
  for try await item in items {
    print("  \(item)")
  }
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudWorkstationsV1.WorkstationsClient()
      try await sample(
        client: client, projectId: "[placeholder]", locationId: "[placeholder]",
        workstationClusterId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
