// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message for creating a CreateWorkstation.
public struct CreateWorkstationRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Parent resource name.
  public var parent: Swift.String = Swift.String()

  /// Required. ID to use for the workstation.
  public var workstationId: Swift.String = Swift.String()

  /// Required. Workstation to create. If source_workstation is specified, the
  /// user must have `workstations.workstations.use` permission on the source
  /// workstation, and the Cloud Workstations Service Agent for the project where
  /// you are creating the new workstation must have compute.disks.createSnapshot
  /// and compute.snapshots.useReadOnly on the source project.
  public var workstation: Workstation? = nil

  /// Optional. If set, validate the request and preview the result, but do not
  /// actually apply it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `CreateWorkstationRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateWorkstationRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workstations.v1.CreateWorkstationRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
