// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message for deleting a workstation cluster.
public struct DeleteWorkstationClusterRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the workstation cluster to delete.
  public var name: Swift.String = Swift.String()

  /// Optional. If set, validate the request and preview the result, but do not
  /// apply it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Optional. If set, the request will be rejected if the latest version of the
  /// workstation cluster on the server does not have this ETag.
  public var etag: Swift.String = Swift.String()

  /// Optional. If set, any workstation configurations and workstations in the
  /// workstation cluster are also deleted. Otherwise, the request only
  /// works if the workstation cluster has no configurations or workstations.
  public var force: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DeleteWorkstationClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteWorkstationClusterRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workstations.v1.DeleteWorkstationClusterRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
