// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for UpdateWorkstationConfig.
public struct UpdateWorkstationConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Workstation configuration to update.
  public var workstationConfig: WorkstationConfig? = nil

  /// Required. Mask specifying which fields in the workstation configuration
  /// should be updated.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Optional. If set, validate the request and preview the result, but do not
  /// actually apply it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Optional. If set and the workstation configuration is not found, a new
  /// workstation configuration will be created. In this situation,
  /// update_mask is ignored.
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdateWorkstationConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateWorkstationConfigRequest().with { $0.workstationConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workstations.v1.UpdateWorkstationConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
