// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for UpdateWorkstationCluster.
public struct UpdateWorkstationClusterRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Workstation cluster to update.
  public var workstationCluster: WorkstationCluster? = nil

  /// Required. Mask that specifies which fields in the workstation cluster
  /// should be updated.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Optional. If set, validate the request and preview the result, but do not
  /// actually apply it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Optional. If set, and the workstation cluster is not found, a new
  /// workstation cluster will be created. In this situation, update_mask is
  /// ignored.
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdateWorkstationClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateWorkstationClusterRequest().with { $0.workstationCluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workstations.v1.UpdateWorkstationClusterRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
