// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for UpdateWorkstation.
public struct UpdateWorkstationRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Workstation to update.
  public var workstation: Workstation? = nil

  /// Required. Mask specifying which fields in the workstation should be
  /// updated.
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// Optional. If set, validate the request and preview the result, but do not
  /// actually apply it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Optional. If set and the workstation is not found, a new workstation is
  /// created. In this situation, update_mask is ignored.
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdateWorkstationRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateWorkstationRequest().with { $0.workstation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workstations.v1.UpdateWorkstationRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
