// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// A workstation configuration resource in the Cloud Workstations API.
///
/// Workstation configurations act as templates for workstations. The workstation
/// configuration defines details such as the workstation virtual machine (VM)
/// instance type, persistent storage, container image defining environment,
/// which IDE or Code Editor to use, and more. Administrators and platform teams
/// can also use [Identity and Access Management
/// (IAM)](https://cloud.google.com/iam/docs/overview) rules to grant access to
/// teams or to individual developers.
public struct WorkstationConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Full name of this workstation configuration.
  public var name: Swift.String = Swift.String()

  /// Optional. Human-readable name for this workstation configuration.
  public var displayName: Swift.String = Swift.String()

  /// Output only. A system-assigned unique identifier for this workstation
  /// configuration.
  public var uid: Swift.String = Swift.String()

  /// Output only. Indicates whether this workstation configuration is currently
  /// being updated to match its intended state.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. Client-specified annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional.
  /// [Labels](https://cloud.google.com/workstations/docs/label-resources) that
  /// are applied to the workstation configuration and that are also propagated
  /// to the underlying Compute Engine resources.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Time when this workstation configuration was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when this workstation configuration was most recently
  /// updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when this workstation configuration was soft-deleted.
  public var deleteTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Checksum computed by the server. May be sent on update and delete
  /// requests to make sure that the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. Number of seconds to wait before automatically stopping a
  /// workstation after it last received user traffic.
  ///
  /// A value of `"0s"` indicates that Cloud Workstations VMs created with this
  /// configuration should never time out due to idleness.
  /// Provide
  /// [duration](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#duration)
  /// terminated by `s` for seconds—for example, `"7200s"` (2 hours).
  /// The default is `"1200s"` (20 minutes).
  public var idleTimeout: GoogleCloudWKT.Duration? = nil

  /// Optional. Number of seconds that a workstation can run until it is
  /// automatically shut down. We recommend that workstations be shut down daily
  /// to reduce costs and so that security updates can be applied upon restart.
  /// The
  /// [idle_timeout][google.cloud.workstations.v1.WorkstationConfig.idle_timeout]
  /// and
  /// [running_timeout][google.cloud.workstations.v1.WorkstationConfig.running_timeout]
  /// fields are independent of each other. Note that the
  /// [running_timeout][google.cloud.workstations.v1.WorkstationConfig.running_timeout]
  /// field shuts down VMs after the specified time, regardless of whether or not
  /// the VMs are idle.
  ///
  /// Provide duration terminated by `s` for seconds—for example, `"54000s"`
  /// (15 hours). Defaults to `"43200s"` (12 hours). A value of `"0s"` indicates
  /// that workstations using this configuration should never time out. If
  /// [encryption_key][google.cloud.workstations.v1.WorkstationConfig.encryption_key]
  /// is set, it must be greater than `"0s"` and less than
  /// `"86400s"` (24 hours).
  ///
  /// Warning: A value of `"0s"` indicates that Cloud Workstations VMs created
  /// with this configuration have no maximum running time. This is strongly
  /// discouraged because you incur costs and will not pick up security updates.
  ///
  /// [google.cloud.workstations.v1.WorkstationConfig.encryption_key]: <doc:WorkstationConfig/encryptionKey>
  /// [google.cloud.workstations.v1.WorkstationConfig.idle_timeout]: <doc:WorkstationConfig/idleTimeout>
  /// [google.cloud.workstations.v1.WorkstationConfig.running_timeout]: <doc:WorkstationConfig/runningTimeout>
  public var runningTimeout: GoogleCloudWKT.Duration? = nil

  /// Optional. Maximum number of workstations under this configuration a user
  /// can have `workstations.workstation.use` permission on.
  ///
  /// Only enforced on CreateWorkstation API calls on the user issuing the API
  /// request. Can be overridden by:
  ///
  /// - granting a user
  /// workstations.workstationConfigs.exemptMaxUsableWorkstationLimit permission,
  /// or
  /// - having a user with that permission create a workstation and
  /// granting another user `workstations.workstation.use` permission on
  /// that workstation.
  ///
  /// If not specified, defaults to `0`, which indicates unlimited.
  public var maxUsableWorkstations: Swift.Int32 = Swift.Int32()

  /// Optional. Runtime host for the workstation.
  public var host: WorkstationConfig.Host? = nil

  /// Optional. Directories to persist across workstation sessions.
  public var persistentDirectories: [WorkstationConfig.PersistentDirectory] = []

  /// Optional. Ephemeral directories which won't persist across workstation
  /// sessions.
  public var ephemeralDirectories: [WorkstationConfig.EphemeralDirectory] = []

  /// Optional. Container that runs upon startup for each workstation using this
  /// workstation configuration.
  public var container: WorkstationConfig.Container? = nil

  /// Immutable. Encrypts resources of this workstation configuration using a
  /// customer-managed encryption key (CMEK).
  ///
  /// If specified, the boot disk of the Compute Engine instance and the
  /// persistent disk are encrypted using this encryption key. If
  /// this field is not set, the disks are encrypted using a generated
  /// key. Customer-managed encryption keys do not protect disk metadata.
  ///
  /// If the customer-managed encryption key is rotated, when the workstation
  /// instance is stopped, the system attempts to recreate the
  /// persistent disk with the new version of the key. Be sure to keep
  /// older versions of the key until the persistent disk is recreated.
  /// Otherwise, data on the persistent disk might be lost.
  ///
  /// If the encryption key is revoked, the workstation session automatically
  /// stops within 7 hours.
  ///
  /// Immutable after the workstation configuration is created.
  public var encryptionKey: WorkstationConfig.CustomerEncryptionKey? = nil

  /// Optional. Readiness checks to perform when starting a workstation using
  /// this workstation configuration. Mark a workstation as running only after
  /// all specified readiness checks return 200 status codes.
  public var readinessChecks: [WorkstationConfig.ReadinessCheck] = []

  /// Optional. Immutable. Specifies the zones used to replicate the VM and disk
  /// resources within the region. If set, exactly two zones within the
  /// workstation cluster's region must be specified—for example,
  /// `['us-central1-a', 'us-central1-f']`. If this field is empty, two default
  /// zones within the region are used.
  ///
  /// Immutable after the workstation configuration is created.
  public var replicaZones: [Swift.String] = []

  /// Output only. Whether this workstation configuration is in degraded mode, in
  /// which case it may require user action to restore full functionality. The
  /// [conditions][google.cloud.workstations.v1.WorkstationConfig.conditions]
  /// field contains detailed information about the status of the configuration.
  ///
  /// [google.cloud.workstations.v1.WorkstationConfig.conditions]: <doc:WorkstationConfig/conditions>
  public var degraded: Swift.Bool = Swift.Bool()

  /// Output only. Status conditions describing the workstation configuration's
  /// current state.
  public var conditions: [GoogleRpc.Status] = []

  /// Optional. Whether to enable Linux `auditd` logging on the workstation. When
  /// enabled, a
  /// [service_account][google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.service_account]
  /// must also be specified that has `roles/logging.logWriter` and
  /// `roles/monitoring.metricWriter` on the project. Operating system audit
  /// logging is distinct from [Cloud Audit
  /// Logs](https://cloud.google.com/workstations/docs/audit-logging) and
  /// [Container output
  /// logging](https://cloud.google.com/workstations/docs/container-output-logging#overview).
  /// Operating system audit logs are available in the
  /// [Cloud Logging](https://cloud.google.com/logging/docs) console by querying:
  ///
  ///     resource.type="gce_instance"
  ///     log_name:"/logs/linux-auditd"
  ///
  /// [google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.service_account]: <doc:WorkstationConfig/Host/GceInstance/serviceAccount>
  public var enableAuditAgent: Swift.Bool = Swift.Bool()

  /// Optional. Disables support for plain TCP connections in the workstation.
  /// By default the service supports TCP connections through a websocket relay.
  /// Setting this option to true disables that relay, which prevents the usage
  /// of services that require plain TCP connections, such as SSH.
  /// When enabled, all communication must occur over HTTPS or WSS.
  public var disableTcpConnections: Swift.Bool = Swift.Bool()

  /// Optional. A list of
  /// [PortRange][google.cloud.workstations.v1.WorkstationConfig.PortRange]s
  /// specifying single ports or ranges of ports that are externally accessible
  /// in the workstation. Allowed ports must be one of 22, 80, or within range
  /// 1024-65535. If not specified defaults to ports 22, 80, and ports
  /// 1024-65535.
  ///
  /// [google.cloud.workstations.v1.WorkstationConfig.PortRange]: <doc:WorkstationConfig/PortRange>
  public var allowedPorts: [WorkstationConfig.PortRange] = []

  /// Optional. Grant creator of a workstation `roles/workstations.policyAdmin`
  /// role along with `roles/workstations.user` role on the workstation created
  /// by them. This allows workstation users to share access to either their
  /// entire workstation, or individual ports. Defaults to false.
  public var grantWorkstationAdminRoleOnCreate: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `WorkstationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkstationConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Runtime host for a workstation.
  public struct Host: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Type of host to be used for the workstation's runtime.
    public var config: OneOf_Config? = nil

    /// Initialize a new instance of `Host`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Host().with { $0.gceInstance = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case gceInstance = "gceInstance"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var config: OneOf_Config? = nil
      let configCheckAndSet = {
        if config != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'config'"))
        }
        config = $0
      }
      if let gceInstance = try container.decodeIfPresent(
        WorkstationConfig.Host.GceInstance?.self, forKey: .gceInstance)
      {
        try configCheckAndSet(.gceInstance(gceInstance))
      }
      self.config = config
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.config {
        switch choice {
        case .gceInstance(let value):
          try container.encode(value, forKey: .gceInstance)
        }
      }
    }

    /// A runtime using a Compute Engine instance.
    public struct GceInstance: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Optional. The type of machine to use for VM instances—for example,
      /// `"e2-standard-4"`. For more information about machine types that
      /// Cloud Workstations supports, see the list of
      /// [available machine
      /// types](https://cloud.google.com/workstations/docs/available-machine-types).
      public var machineType: Swift.String = Swift.String()

      /// Optional. The email address of the service account for Cloud
      /// Workstations VMs created with this configuration. When specified, be
      /// sure that the service account has `logging.logEntries.create` and
      /// `monitoring.timeSeries.create` permissions on the project so it can
      /// write logs out to Cloud Logging. If using a custom container image, the
      /// service account must have [Artifact Registry
      /// Reader](https://cloud.google.com/artifact-registry/docs/access-control#roles)
      /// permission to pull the specified image.
      ///
      /// If you as the administrator want to be able to `ssh` into the
      /// underlying VM, you need to set this value to a service account
      /// for which you have the `iam.serviceAccounts.actAs` permission.
      /// Conversely, if you don't want anyone to be able to `ssh` into the
      /// underlying VM, use a service account where no one has that
      /// permission.
      ///
      /// If not set, VMs run with a service account provided by the
      /// Cloud Workstations service, and the image must be publicly
      /// accessible.
      public var serviceAccount: Swift.String = Swift.String()

      /// Optional. Scopes to grant to the
      /// [service_account][google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.service_account].
      /// When specified, users of workstations under this configuration must
      /// have `iam.serviceAccounts.actAs` on the service account.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.service_account]: <doc:WorkstationConfig/Host/GceInstance/serviceAccount>
      public var serviceAccountScopes: [Swift.String] = []

      /// Optional. Network tags to add to the Compute Engine VMs backing the
      /// workstations. This option applies
      /// [network
      /// tags](https://cloud.google.com/vpc/docs/add-remove-network-tags) to VMs
      /// created with this configuration. These network tags enable the creation
      /// of [firewall
      /// rules](https://cloud.google.com/workstations/docs/configure-firewall-rules).
      public var tags: [Swift.String] = []

      /// Optional. The number of VMs that the system should keep idle so that
      /// new workstations can be started quickly for new users. Defaults to `0`
      /// in the API.
      public var poolSize: Swift.Int32 = Swift.Int32()

      /// Output only. Number of instances currently available in the pool for
      /// faster workstation startup.
      public var pooledInstances: Swift.Int32 = Swift.Int32()

      /// Optional. When set to true, disables public IP addresses for VMs. If
      /// you disable public IP addresses, you must set up Private Google Access
      /// or Cloud NAT on your network. If you use Private Google Access and you
      /// use `private.googleapis.com` or `restricted.googleapis.com` for
      /// Container Registry and Artifact Registry, make sure that you set
      /// up DNS records for domains `*.gcr.io` and `*.pkg.dev`.
      /// Defaults to false (VMs have public IP addresses).
      public var disablePublicIpAddresses: Swift.Bool = Swift.Bool()

      /// Optional. Whether to enable nested virtualization on Cloud Workstations
      /// VMs created using this workstation configuration.
      ///
      /// Defaults to false.
      ///
      /// Nested virtualization lets you run virtual machine (VM) instances
      /// inside your workstation. Before enabling nested virtualization,
      /// consider the following important considerations. Cloud Workstations
      /// instances are subject to the [same restrictions as Compute Engine
      /// instances](https://cloud.google.com/compute/docs/instances/nested-virtualization/overview#restrictions):
      ///
      /// * **Organization policy**: projects, folders, or
      /// organizations may be restricted from creating nested VMs if the
      /// **Disable VM nested virtualization** constraint is enforced in
      /// the organization policy. For more information, see the
      /// Compute Engine section,
      /// [Checking whether nested virtualization is
      /// allowed](https://cloud.google.com/compute/docs/instances/nested-virtualization/managing-constraint#checking_whether_nested_virtualization_is_allowed).
      /// * **Performance**: nested VMs might experience a 10% or greater
      /// decrease in performance for workloads that are CPU-bound and
      /// possibly greater than a 10% decrease for workloads that are
      /// input/output bound.
      /// * **Machine Type**: nested virtualization can only be enabled on
      /// workstation configurations that specify a
      /// [machine_type][google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.machine_type]
      /// in the N1 or N2 machine series.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.machine_type]: <doc:WorkstationConfig/Host/GceInstance/machineType>
      public var enableNestedVirtualization: Swift.Bool = Swift.Bool()

      /// Optional. A set of Compute Engine Shielded instance options.
      public var shieldedInstanceConfig:
        WorkstationConfig.Host.GceInstance.GceShieldedInstanceConfig? = nil

      /// Optional. A set of Compute Engine Confidential VM instance options.
      public var confidentialInstanceConfig:
        WorkstationConfig.Host.GceInstance.GceConfidentialInstanceConfig? = nil

      /// Optional. The size of the boot disk for the VM in gigabytes (GB).
      /// The minimum boot disk size is `30` GB. Defaults to `50` GB.
      public var bootDiskSizeGb: Swift.Int32 = Swift.Int32()

      /// Optional. A list of the type and count of accelerator cards attached to
      /// the instance.
      public var accelerators: [WorkstationConfig.Host.GceInstance.Accelerator] = []

      /// Optional. A list of the boost configurations that workstations created
      /// using this workstation configuration are allowed to use. If specified,
      /// users will have the option to choose from the list of boost configs
      /// when starting a workstation.
      public var boostConfigs: [WorkstationConfig.Host.GceInstance.BoostConfig] = []

      /// Optional. Whether to disable SSH access to the VM.
      public var disableSsh: Swift.Bool = Swift.Bool()

      /// Optional. Resource manager tags to be bound to this instance.
      /// Tag keys and values have the same definition as [resource manager
      /// tags](https://cloud.google.com/resource-manager/docs/tags/tags-overview).
      /// Keys must be in the format `tagKeys/{tag_key_id}`, and
      /// values are in the format `tagValues/456`.
      public var vmTags: [Swift.String: Swift.String] = [:]

      /// Optional. Link to the startup script stored in Cloud Storage. This
      /// script will be run on the host workstation VM when the VM is created.
      /// The URI must be of the form gs://{bucket-name}/{object-name}. If
      /// specifying a startup script, the service account must have [Permission
      /// to access the bucket and script file in Cloud
      /// Storage](https://cloud.google.com/storage/docs/access-control/iam-permissions).
      /// Otherwise, the script must be publicly accessible.
      /// Note that the service regularly updates the OS version of the host VM,
      /// and it is the responsibility of the user to ensure the script stays
      /// compatible with the OS version.
      public var startupScriptUri: Swift.String = Swift.String()

      /// Optional. Custom metadata to apply to Compute Engine instances.
      public var instanceMetadata: [Swift.String: Swift.String] = [:]

      /// Initialize a new instance of `GceInstance`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GceInstance().with { $0.machineType = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// A set of Compute Engine Shielded instance options.
      public struct GceShieldedInstanceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
        Sendable
      {
        /// Optional. Whether the instance has Secure Boot enabled.
        public var enableSecureBoot: Swift.Bool = Swift.Bool()

        /// Optional. Whether the instance has the vTPM enabled.
        public var enableVtpm: Swift.Bool = Swift.Bool()

        /// Optional. Whether the instance has integrity monitoring enabled.
        public var enableIntegrityMonitoring: Swift.Bool = Swift.Bool()

        /// Initialize a new instance of `GceShieldedInstanceConfig`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = GceShieldedInstanceConfig().with { $0.enableSecureBoot = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.GceShieldedInstanceConfig"
        }
        public init(fromAny any: GoogleCloudWKT.`Any`) throws {
          self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWKT.Struct {
          return try GoogleCloudWKT._slowAnySerialize(message: self)
        }
      }

      /// A set of Compute Engine Confidential VM instance options.
      public struct GceConfidentialInstanceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
        Sendable
      {
        /// Optional. Whether the instance has confidential compute enabled.
        public var enableConfidentialCompute: Swift.Bool = Swift.Bool()

        /// Initialize a new instance of `GceConfidentialInstanceConfig`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = GceConfidentialInstanceConfig().with { $0.enableConfidentialCompute = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.GceConfidentialInstanceConfig"
        }
        public init(fromAny any: GoogleCloudWKT.`Any`) throws {
          self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWKT.Struct {
          return try GoogleCloudWKT._slowAnySerialize(message: self)
        }
      }

      /// An accelerator card attached to the instance.
      public struct Accelerator: Codable, Equatable, GoogleCloudWKT._AnyPackable,
        Sendable
      {
        /// Optional. Type of accelerator resource to attach to the instance, for
        /// example,
        /// `"nvidia-tesla-p100"`.
        public var type: Swift.String = Swift.String()

        /// Optional. Number of accelerator cards exposed to the instance.
        public var count: Swift.Int32 = Swift.Int32()

        /// Initialize a new instance of `Accelerator`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Accelerator().with { $0.type = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.Accelerator"
        }
        public init(fromAny any: GoogleCloudWKT.`Any`) throws {
          self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWKT.Struct {
          return try GoogleCloudWKT._slowAnySerialize(message: self)
        }
      }

      /// A boost configuration is a set of resources that a workstation can use
      /// to increase its performance. If you specify a boost configuration, upon
      /// startup, workstation users can choose to use a VM provisioned under the
      /// boost config by passing the boost config ID in the start request. If
      /// the workstation user does not provide a boost config ID  in the start
      /// request, the system will choose a VM from the pool provisioned under
      /// the default config.
      public struct BoostConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
        Sendable
      {
        /// Required. The ID to be used for the boost configuration.
        public var id: Swift.String = Swift.String()

        /// Optional. The type of machine that boosted VM instances will use—for
        /// example, `e2-standard-4`. For more information about machine types
        /// that Cloud Workstations supports, see the list of [available machine
        /// types](https://cloud.google.com/workstations/docs/available-machine-types).
        /// Defaults to `e2-standard-4`.
        public var machineType: Swift.String = Swift.String()

        /// Optional. A list of the type and count of accelerator cards attached
        /// to the boost instance. Defaults to `none`.
        public var accelerators: [WorkstationConfig.Host.GceInstance.Accelerator] = []

        /// Optional. The size of the boot disk for the VM in gigabytes (GB).
        /// The minimum boot disk size is `30` GB. Defaults to `50` GB.
        public var bootDiskSizeGb: Swift.Int32 = Swift.Int32()

        /// Optional. Whether to enable nested virtualization on boosted Cloud
        /// Workstations VMs running using this boost configuration.
        ///
        /// Defaults to false.
        ///
        /// Nested virtualization lets you run virtual machine (VM) instances
        /// inside your workstation. Before enabling nested virtualization,
        /// consider the following important considerations. Cloud Workstations
        /// instances are subject to the [same restrictions as Compute Engine
        /// instances](https://cloud.google.com/compute/docs/instances/nested-virtualization/overview#restrictions):
        ///
        /// * **Organization policy**: projects, folders, or
        /// organizations may be restricted from creating nested VMs if the
        /// **Disable VM nested virtualization** constraint is enforced in
        /// the organization policy. For more information, see the
        /// Compute Engine section,
        /// [Checking whether nested virtualization is
        /// allowed](https://cloud.google.com/compute/docs/instances/nested-virtualization/managing-constraint#checking_whether_nested_virtualization_is_allowed).
        /// * **Performance**: nested VMs might experience a 10% or greater
        /// decrease in performance for workloads that are CPU-bound and
        /// possibly greater than a 10% decrease for workloads that are
        /// input/output bound.
        /// * **Machine Type**: nested virtualization can only be enabled on
        /// boost configurations that specify a
        /// [machine_type][google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.BoostConfig.machine_type]
        /// in the N1 or N2 machine series.
        ///
        /// [google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.BoostConfig.machine_type]: <doc:WorkstationConfig/Host/GceInstance/BoostConfig/machineType>
        public var enableNestedVirtualization: Swift.Bool = Swift.Bool()

        /// Optional. The number of boost VMs that the system should keep idle so
        /// that workstations can be boosted quickly. Defaults to `0`.
        public var poolSize: Swift.Int32 = Swift.Int32()

        /// Initialize a new instance of `BoostConfig`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = BoostConfig().with { $0.id = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance.BoostConfig"
        }
        public init(fromAny any: GoogleCloudWKT.`Any`) throws {
          self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWKT.Struct {
          return try GoogleCloudWKT._slowAnySerialize(message: self)
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.Host.GceInstance"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Type of host to be used for the workstation's runtime.
    public enum OneOf_Config: Codable, Equatable, Sendable {
      /// Specifies a Compute Engine instance as the host.
      indirect case gceInstance(WorkstationConfig.Host.GceInstance?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.Host"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A directory to persist across workstation sessions. Updates to this field
  /// will not update existing workstations and will only take effect on new
  /// workstations.
  public struct PersistentDirectory: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Location of this directory in the running workstation.
    public var mountPath: Swift.String = Swift.String()

    /// How a persistent directory should be implemented.
    public var directoryType: OneOf_DirectoryType? = nil

    /// Initialize a new instance of `PersistentDirectory`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PersistentDirectory().with { $0.gcePd = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case gcePd = "gcePd"
      case gceHd = "gceHd"
      case mountPath = "mountPath"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.mountPath = try container.decode(Swift.String.self, forKey: .mountPath)

      var directoryType: OneOf_DirectoryType? = nil
      let directoryTypeCheckAndSet = {
        if directoryType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'directoryType'"))
        }
        directoryType = $0
      }
      if let gcePd = try container.decodeIfPresent(
        WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk?.self, forKey: .gcePd)
      {
        try directoryTypeCheckAndSet(.gcePd(gcePd))
      }
      if let gceHd = try container.decodeIfPresent(
        WorkstationConfig.PersistentDirectory.GceHyperdiskBalancedHighAvailability?.self,
        forKey: .gceHd)
      {
        try directoryTypeCheckAndSet(.gceHd(gceHd))
      }
      self.directoryType = directoryType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.mountPath, forKey: .mountPath)

      if let choice = self.directoryType {
        switch choice {
        case .gcePd(let value):
          try container.encode(value, forKey: .gcePd)
        case .gceHd(let value):
          try container.encode(value, forKey: .gceHd)
        }
      }
    }

    /// A Persistent Directory backed by a Compute Engine regional persistent
    /// disk. The
    /// [persistent_directories][google.cloud.workstations.v1.WorkstationConfig.persistent_directories]
    /// field is repeated, but it may contain only one entry. It creates a
    /// [persistent
    /// disk](https://cloud.google.com/compute/docs/disks/persistent-disks) that
    /// mounts to the workstation VM at `/home` when the session starts and
    /// detaches when the session ends. If this field is empty, workstations
    /// created with this configuration do not have a persistent home
    /// directory.
    ///
    /// [google.cloud.workstations.v1.WorkstationConfig.persistent_directories]: <doc:WorkstationConfig/persistentDirectories>
    public struct GceRegionalPersistentDisk: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Optional. The GB capacity of a persistent home directory for each
      /// workstation created with this configuration. Must be empty if
      /// [source_snapshot][google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.source_snapshot]
      /// is set.
      ///
      /// Valid values are `10`, `50`, `100`, `200`, `500`, or `1000`.
      /// Defaults to `200`. If less than `200` GB, the
      /// [disk_type][google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.disk_type]
      /// must be
      /// `"pd-balanced"` or `"pd-ssd"`.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.disk_type]: <doc:WorkstationConfig/PersistentDirectory/GceRegionalPersistentDisk/diskType>
      /// [google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.source_snapshot]: <doc:WorkstationConfig/PersistentDirectory/GceRegionalPersistentDisk/sourceSnapshot>
      public var sizeGb: Swift.Int32 = Swift.Int32()

      /// Optional. Maximum size in GB to which this persistent directory can be
      /// resized. Defaults to unlimited if not set.
      public var maxSizeGb: Swift.Int32 = Swift.Int32()

      /// Optional. Type of file system that the disk should be formatted with.
      /// The workstation image must support this file system type. Must be empty
      /// if
      /// [source_snapshot][google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.source_snapshot]
      /// is set. Defaults to `"ext4"`.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.source_snapshot]: <doc:WorkstationConfig/PersistentDirectory/GceRegionalPersistentDisk/sourceSnapshot>
      public var fsType: Swift.String = Swift.String()

      /// Optional. The [type of the persistent
      /// disk](https://cloud.google.com/compute/docs/disks#disk-types) for the
      /// home directory. Defaults to `"pd-standard"`.
      public var diskType: Swift.String = Swift.String()

      /// Optional. Name of the snapshot to use as the source for the disk. If
      /// set,
      /// [size_gb][google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.size_gb]
      /// and
      /// [fs_type][google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.fs_type]
      /// must be empty. Must be formatted as ext4 file system with no
      /// partitions.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.fs_type]: <doc:WorkstationConfig/PersistentDirectory/GceRegionalPersistentDisk/fsType>
      /// [google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.size_gb]: <doc:WorkstationConfig/PersistentDirectory/GceRegionalPersistentDisk/sizeGb>
      public var sourceSnapshot: Swift.String = Swift.String()

      /// Optional. Whether the persistent disk should be deleted when the
      /// workstation is deleted. Valid values are `DELETE` and `RETAIN`.
      /// Defaults to `DELETE`.
      public var reclaimPolicy:
        WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.ReclaimPolicy =
          WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk.ReclaimPolicy()

      /// Optional. Number of seconds to wait after initially creating or
      /// subsequently shutting down the workstation before converting its disk
      /// into a snapshot. This generally saves costs at the expense of greater
      /// startup time on next workstation start, as the service will need to
      /// create a disk from the archival snapshot.
      ///
      /// A value of `"0s"` indicates that the disk will never be archived.
      public var archiveTimeout: GoogleCloudWKT.Duration? = nil

      /// Initialize a new instance of `GceRegionalPersistentDisk`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GceRegionalPersistentDisk().with { $0.sizeGb = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Value representing what should happen to the disk after the workstation
      /// is deleted.
      public enum ReclaimPolicy: Codable, Equatable, Sendable {
        /// Do not use.
        case unspecified
        /// Delete the persistent disk when deleting the workstation.
        case delete
        /// Keep the persistent disk when deleting the workstation.
        /// An administrator must manually delete the disk.
        case retain
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .delete: return 1
          case .retain: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "RECLAIM_POLICY_UNSPECIFIED"
          case .delete: return "DELETE"
          case .retain: return "RETAIN"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReclaimPolicy/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "RECLAIM_POLICY_UNSPECIFIED": self = .unspecified
          case "DELETE": self = .delete
          case "RETAIN": self = .retain
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReclaimPolicy/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .delete
          case 2: self = .retain
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .delete: return try container.encode(1)
          case .retain: return try container.encode(2)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// A Persistent Directory backed by a Compute Engine
    /// [Hyperdisk Balanced High Availability
    /// Disk](https://cloud.google.com/compute/docs/disks/hd-types/hyperdisk-balanced-ha).
    /// This is a high-availability block storage solution that offers a balance
    /// between performance and cost for most general-purpose workloads.
    public struct GceHyperdiskBalancedHighAvailability: Codable, Equatable, GoogleCloudWKT
        ._AnyPackable,
      Sendable
    {
      /// Optional. The GB capacity of a persistent home directory for each
      /// workstation created with this configuration. Must be empty if
      /// [source_snapshot][google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceHyperdiskBalancedHighAvailability.source_snapshot]
      /// is set.
      ///
      /// Valid values are `10`, `50`, `100`, `200`, `500`, or `1000`.
      /// Defaults to `200`.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceHyperdiskBalancedHighAvailability.source_snapshot]: <doc:WorkstationConfig/PersistentDirectory/GceHyperdiskBalancedHighAvailability/sourceSnapshot>
      public var sizeGb: Swift.Int32 = Swift.Int32()

      /// Optional. Maximum size in GB to which this persistent directory can be
      /// resized. Defaults to unlimited if not set.
      public var maxSizeGb: Swift.Int32 = Swift.Int32()

      /// Optional. Name of the snapshot to use as the source for the disk. If
      /// set,
      /// [size_gb][google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceHyperdiskBalancedHighAvailability.size_gb]
      /// must be empty. Must be formatted as ext4 file system with no
      /// partitions.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceHyperdiskBalancedHighAvailability.size_gb]: <doc:WorkstationConfig/PersistentDirectory/GceHyperdiskBalancedHighAvailability/sizeGb>
      public var sourceSnapshot: Swift.String = Swift.String()

      /// Optional. Whether the persistent disk should be deleted when the
      /// workstation is deleted. Valid values are `DELETE` and `RETAIN`.
      /// Defaults to `DELETE`.
      public var reclaimPolicy:
        WorkstationConfig.PersistentDirectory.GceHyperdiskBalancedHighAvailability.ReclaimPolicy =
          WorkstationConfig.PersistentDirectory.GceHyperdiskBalancedHighAvailability.ReclaimPolicy()

      /// Optional. Number of seconds to wait after initially creating or
      /// subsequently shutting down the workstation before converting its disk
      /// into a snapshot. This generally saves costs at the expense of greater
      /// startup time on next workstation start, as the service will need to
      /// create a disk from the archival snapshot.
      ///
      /// A value of `"0s"` indicates that the disk will never be archived.
      public var archiveTimeout: GoogleCloudWKT.Duration? = nil

      /// Initialize a new instance of `GceHyperdiskBalancedHighAvailability`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GceHyperdiskBalancedHighAvailability().with { $0.sizeGb = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Value representing what should happen to the disk after the workstation
      /// is deleted.
      public enum ReclaimPolicy: Codable, Equatable, Sendable {
        /// Do not use.
        case unspecified
        /// Delete the persistent disk when deleting the workstation.
        case delete
        /// Keep the persistent disk when deleting the workstation.
        /// An administrator must manually delete the disk.
        case retain
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .delete: return 1
          case .retain: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "RECLAIM_POLICY_UNSPECIFIED"
          case .delete: return "DELETE"
          case .retain: return "RETAIN"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReclaimPolicy/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "RECLAIM_POLICY_UNSPECIFIED": self = .unspecified
          case "DELETE": self = .delete
          case "RETAIN": self = .retain
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReclaimPolicy/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .delete
          case 2: self = .retain
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .delete: return try container.encode(1)
          case .retain: return try container.encode(2)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory.GceHyperdiskBalancedHighAvailability"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// How a persistent directory should be implemented.
    public enum OneOf_DirectoryType: Codable, Equatable, Sendable {
      /// A PersistentDirectory backed by a Compute Engine persistent disk.
      indirect case gcePd(WorkstationConfig.PersistentDirectory.GceRegionalPersistentDisk?)
      /// A PersistentDirectory backed by a Compute Engine hyperdisk high
      /// availability disk.
      indirect case gceHd(
        WorkstationConfig.PersistentDirectory.GceHyperdiskBalancedHighAvailability?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.PersistentDirectory"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// An ephemeral directory which won't persist across workstation sessions. It
  /// is freshly created on every workstation start operation.
  public struct EphemeralDirectory: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Location of this directory in the running workstation.
    public var mountPath: Swift.String = Swift.String()

    /// How an ephemeral directory should be implemented.
    public var directoryType: OneOf_DirectoryType? = nil

    /// Initialize a new instance of `EphemeralDirectory`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EphemeralDirectory().with { $0.gcePd = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case gcePd = "gcePd"
      case mountPath = "mountPath"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.mountPath = try container.decode(Swift.String.self, forKey: .mountPath)

      var directoryType: OneOf_DirectoryType? = nil
      let directoryTypeCheckAndSet = {
        if directoryType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'directoryType'"))
        }
        directoryType = $0
      }
      if let gcePd = try container.decodeIfPresent(
        WorkstationConfig.EphemeralDirectory.GcePersistentDisk?.self, forKey: .gcePd)
      {
        try directoryTypeCheckAndSet(.gcePd(gcePd))
      }
      self.directoryType = directoryType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.mountPath, forKey: .mountPath)

      if let choice = self.directoryType {
        switch choice {
        case .gcePd(let value):
          try container.encode(value, forKey: .gcePd)
        }
      }
    }

    /// An EphemeralDirectory is backed by a Compute Engine persistent disk.
    public struct GcePersistentDisk: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Optional. Type of the disk to use. Defaults to `"pd-standard"`.
      public var diskType: Swift.String = Swift.String()

      /// Optional. Name of the snapshot to use as the source for the disk. Must
      /// be empty if
      /// [source_image][google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_image]
      /// is set. Must be empty if
      /// [read_only][google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.read_only]
      /// is false. Updating
      /// [source_snapshot][google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_snapshot]
      /// will update content in the ephemeral directory after the workstation is
      /// restarted.
      ///
      /// Only file systems supported by Container-Optimized OS (COS)
      /// are explicitly supported. For a list of supported file systems, see
      /// [the filesystems available in Container-Optimized
      /// OS](https://cloud.google.com/container-optimized-os/docs/concepts/supported-filesystems).
      ///
      /// This field is mutable.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.read_only]: <doc:WorkstationConfig/EphemeralDirectory/GcePersistentDisk/readOnly>
      /// [google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_image]: <doc:WorkstationConfig/EphemeralDirectory/GcePersistentDisk/sourceImage>
      /// [google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_snapshot]: <doc:WorkstationConfig/EphemeralDirectory/GcePersistentDisk/sourceSnapshot>
      public var sourceSnapshot: Swift.String = Swift.String()

      /// Optional. Name of the disk image to use as the source for the disk.
      /// Must be empty if
      /// [source_snapshot][google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_snapshot]
      /// is set. Updating
      /// [source_image][google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_image]
      /// will update content in the ephemeral directory after the workstation is
      /// restarted.
      ///
      /// Only file systems supported by Container-Optimized OS (COS)
      /// are explicitly supported. For a list of supported file systems, please
      /// refer to the [COS
      /// documentation](https://cloud.google.com/container-optimized-os/docs/concepts/supported-filesystems).
      ///
      /// This field is mutable.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_image]: <doc:WorkstationConfig/EphemeralDirectory/GcePersistentDisk/sourceImage>
      /// [google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_snapshot]: <doc:WorkstationConfig/EphemeralDirectory/GcePersistentDisk/sourceSnapshot>
      public var sourceImage: Swift.String = Swift.String()

      /// Optional. Whether the disk is read only. If true, the disk may be
      /// shared by multiple VMs and
      /// [source_snapshot][google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_snapshot]
      /// must be set.
      ///
      /// [google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk.source_snapshot]: <doc:WorkstationConfig/EphemeralDirectory/GcePersistentDisk/sourceSnapshot>
      public var readOnly: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `GcePersistentDisk`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GcePersistentDisk().with { $0.diskType = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory.GcePersistentDisk"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// How an ephemeral directory should be implemented.
    public enum OneOf_DirectoryType: Codable, Equatable, Sendable {
      /// An EphemeralDirectory backed by a Compute Engine persistent disk.
      indirect case gcePd(WorkstationConfig.EphemeralDirectory.GcePersistentDisk?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.EphemeralDirectory"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A Docker container.
  public struct Container: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. A Docker container image that defines a custom environment.
    ///
    /// Cloud Workstations provides a number of
    /// [preconfigured
    /// images](https://cloud.google.com/workstations/docs/preconfigured-base-images),
    /// but you can create your own
    /// [custom container
    /// images](https://cloud.google.com/workstations/docs/custom-container-images).
    /// If using a private image, the `host.gceInstance.serviceAccount` field
    /// must be specified in the workstation configuration.
    /// If using a custom container image, the service account must have
    /// [Artifact Registry
    /// Reader](https://cloud.google.com/artifact-registry/docs/access-control#roles)
    /// permission to pull the specified image. Otherwise, the image must be
    /// publicly accessible.
    public var image: Swift.String = Swift.String()

    /// Optional. If set, overrides the default ENTRYPOINT specified by the
    /// image.
    public var command: [Swift.String] = []

    /// Optional. Arguments passed to the entrypoint.
    public var args: [Swift.String] = []

    /// Optional. Environment variables passed to the container's entrypoint.
    public var env: [Swift.String: Swift.String] = [:]

    /// Optional. If set, overrides the default DIR specified by the image.
    public var workingDir: Swift.String = Swift.String()

    /// Optional. If set, overrides the USER specified in the image with the
    /// given uid.
    public var runAsUser: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Container`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Container().with { $0.image = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.Container"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A customer-managed encryption key (CMEK) for the Compute Engine
  /// resources of the associated workstation configuration. Specify the name of
  /// your Cloud KMS encryption key and the default service account.
  /// We recommend that you use a separate service account and follow
  /// [Cloud KMS best
  /// practices](https://cloud.google.com/kms/docs/separation-of-duties).
  public struct CustomerEncryptionKey: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Immutable. The name of the Google Cloud KMS encryption key. For example,
    /// `"projects/PROJECT_ID/locations/REGION/keyRings/KEY_RING/cryptoKeys/KEY_NAME"`.
    /// The key must be in the same region as the workstation configuration.
    public var kmsKey: Swift.String = Swift.String()

    /// Immutable. The service account to use with the specified
    /// KMS key. We recommend that you use a separate service account
    /// and follow KMS best practices. For more information, see
    /// [Separation of
    /// duties](https://cloud.google.com/kms/docs/separation-of-duties) and
    /// `gcloud kms keys add-iam-policy-binding`
    /// [`--member`](https://cloud.google.com/sdk/gcloud/reference/kms/keys/add-iam-policy-binding#--member).
    public var kmsKeyServiceAccount: Swift.String = Swift.String()

    /// Initialize a new instance of `CustomerEncryptionKey`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomerEncryptionKey().with { $0.kmsKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.CustomerEncryptionKey"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A readiness check to be performed on a workstation.
  public struct ReadinessCheck: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Path to which the request should be sent.
    public var path: Swift.String = Swift.String()

    /// Optional. Port to which the request should be sent.
    public var port: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `ReadinessCheck`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReadinessCheck().with { $0.path = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.ReadinessCheck"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A PortRange defines a range of ports. Both
  /// [first][google.cloud.workstations.v1.WorkstationConfig.PortRange.first] and
  /// [last][google.cloud.workstations.v1.WorkstationConfig.PortRange.last] are
  /// inclusive.
  /// To specify a single port, both
  /// [first][google.cloud.workstations.v1.WorkstationConfig.PortRange.first] and
  /// [last][google.cloud.workstations.v1.WorkstationConfig.PortRange.last]
  /// should be the same.
  ///
  /// [google.cloud.workstations.v1.WorkstationConfig.PortRange.first]: <doc:WorkstationConfig/PortRange/first>
  /// [google.cloud.workstations.v1.WorkstationConfig.PortRange.last]: <doc:WorkstationConfig/PortRange/last>
  public struct PortRange: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Starting port number for the current range of ports.
    /// Valid ports are 22, 80, and ports within the range 1024-65535.
    public var first: Swift.Int32 = Swift.Int32()

    /// Required. Ending port number for the current range of ports.
    /// Valid ports are 22, 80, and ports within the range 1024-65535.
    public var last: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `PortRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PortRange().with { $0.first = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig.PortRange"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workstations.v1.WorkstationConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
