// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Service for interacting with Cloud Workstations.
///
/// @Snippet(path: "WorkstationsQuickstart")
public class WorkstationsClient: Clients.WorkstationsProtocol {
  let inner: any Clients.WorkstationsStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `WorkstationsClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.WorkstationsStub = try Clients.WorkstationsTransport(options)
    inner = Clients.WorkstationsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.WorkstationsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Returns the requested workstation cluster.
  ///
  /// @Snippet(path: "Workstations_GetWorkstationCluster")
  public func getWorkstationCluster(
    request: GetWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster {
    try await self.inner.getWorkstationCluster(request: request, options: options)
  }

  /// Returns all workstation clusters in the specified location.
  ///
  /// @Snippet(path: "Workstations_ListWorkstationClusters")
  public func listWorkstationClusters(
    request: ListWorkstationClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse {
    try await self.inner.listWorkstationClusters(request: request, options: options)
  }

  /// Returns all workstation clusters in the specified location.
  ///
  /// @Snippet(path: "Workstations_ListWorkstationClusters")
  public func listWorkstationClusters(
    byItem: ListWorkstationClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<WorkstationCluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listWorkstationClusters(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a new workstation cluster.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstationCluster")
  public func createWorkstationCluster(
    request: CreateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createWorkstationCluster(request: request, options: options)
  }

  /// Creates a new workstation cluster.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstationCluster")
  public func createWorkstationCluster(
    withPolling: CreateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<WorkstationCluster>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try WorkstationCluster(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createWorkstationCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an existing workstation cluster.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstationCluster")
  public func updateWorkstationCluster(
    request: UpdateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateWorkstationCluster(request: request, options: options)
  }

  /// Updates an existing workstation cluster.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstationCluster")
  public func updateWorkstationCluster(
    withPolling: UpdateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<WorkstationCluster>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try WorkstationCluster(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateWorkstationCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified workstation cluster.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstationCluster")
  public func deleteWorkstationCluster(
    request: DeleteWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteWorkstationCluster(request: request, options: options)
  }

  /// Deletes the specified workstation cluster.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstationCluster")
  public func deleteWorkstationCluster(
    withPolling: DeleteWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<WorkstationCluster>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try WorkstationCluster(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteWorkstationCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Returns the requested workstation configuration.
  ///
  /// @Snippet(path: "Workstations_GetWorkstationConfig")
  public func getWorkstationConfig(
    request: GetWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig {
    try await self.inner.getWorkstationConfig(request: request, options: options)
  }

  /// Returns all workstation configurations in the specified cluster.
  ///
  /// @Snippet(path: "Workstations_ListWorkstationConfigs")
  public func listWorkstationConfigs(
    request: ListWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse {
    try await self.inner.listWorkstationConfigs(request: request, options: options)
  }

  /// Returns all workstation configurations in the specified cluster.
  ///
  /// @Snippet(path: "Workstations_ListWorkstationConfigs")
  public func listWorkstationConfigs(
    byItem: ListWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listWorkstationConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns all workstation configurations in the specified cluster on which
  /// the caller has the "workstations.workstation.create" permission.
  ///
  /// @Snippet(path: "Workstations_ListUsableWorkstationConfigs")
  public func listUsableWorkstationConfigs(
    request: ListUsableWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse {
    try await self.inner.listUsableWorkstationConfigs(request: request, options: options)
  }

  /// Returns all workstation configurations in the specified cluster on which
  /// the caller has the "workstations.workstation.create" permission.
  ///
  /// @Snippet(path: "Workstations_ListUsableWorkstationConfigs")
  public func listUsableWorkstationConfigs(
    byItem: ListUsableWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listUsableWorkstationConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a new workstation configuration.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstationConfig")
  public func createWorkstationConfig(
    request: CreateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createWorkstationConfig(request: request, options: options)
  }

  /// Creates a new workstation configuration.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstationConfig")
  public func createWorkstationConfig(
    withPolling: CreateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<WorkstationConfig>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try WorkstationConfig(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createWorkstationConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an existing workstation configuration.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstationConfig")
  public func updateWorkstationConfig(
    request: UpdateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateWorkstationConfig(request: request, options: options)
  }

  /// Updates an existing workstation configuration.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstationConfig")
  public func updateWorkstationConfig(
    withPolling: UpdateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<WorkstationConfig>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try WorkstationConfig(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateWorkstationConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified workstation configuration.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstationConfig")
  public func deleteWorkstationConfig(
    request: DeleteWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteWorkstationConfig(request: request, options: options)
  }

  /// Deletes the specified workstation configuration.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstationConfig")
  public func deleteWorkstationConfig(
    withPolling: DeleteWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<WorkstationConfig>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try WorkstationConfig(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteWorkstationConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Returns the requested workstation.
  ///
  /// @Snippet(path: "Workstations_GetWorkstation")
  public func getWorkstation(
    request: GetWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.Workstation {
    try await self.inner.getWorkstation(request: request, options: options)
  }

  /// Returns all Workstations using the specified workstation configuration.
  ///
  /// @Snippet(path: "Workstations_ListWorkstations")
  public func listWorkstations(
    request: ListWorkstationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationsResponse {
    try await self.inner.listWorkstations(request: request, options: options)
  }

  /// Returns all Workstations using the specified workstation configuration.
  ///
  /// @Snippet(path: "Workstations_ListWorkstations")
  public func listWorkstations(
    byItem: ListWorkstationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workstation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkstationsV1.ListWorkstationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listWorkstations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns all workstations using the specified workstation configuration
  /// on which the caller has the "workstations.workstations.use" permission.
  ///
  /// @Snippet(path: "Workstations_ListUsableWorkstations")
  public func listUsableWorkstations(
    request: ListUsableWorkstationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse {
    try await self.inner.listUsableWorkstations(request: request, options: options)
  }

  /// Returns all workstations using the specified workstation configuration
  /// on which the caller has the "workstations.workstations.use" permission.
  ///
  /// @Snippet(path: "Workstations_ListUsableWorkstations")
  public func listUsableWorkstations(
    byItem: ListUsableWorkstationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workstation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listUsableWorkstations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a new workstation.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstation")
  public func createWorkstation(
    request: CreateWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createWorkstation(request: request, options: options)
  }

  /// Creates a new workstation.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstation")
  public func createWorkstation(
    withPolling: CreateWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Workstation(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createWorkstation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an existing workstation.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstation")
  public func updateWorkstation(
    request: UpdateWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateWorkstation(request: request, options: options)
  }

  /// Updates an existing workstation.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstation")
  public func updateWorkstation(
    withPolling: UpdateWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Workstation(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateWorkstation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified workstation.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstation")
  public func deleteWorkstation(
    request: DeleteWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteWorkstation(request: request, options: options)
  }

  /// Deletes the specified workstation.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstation")
  public func deleteWorkstation(
    withPolling: DeleteWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Workstation(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteWorkstation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Starts running a workstation so that users can connect to it.
  ///
  /// @Snippet(path: "Workstations_StartWorkstation")
  public func startWorkstation(
    request: StartWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.startWorkstation(request: request, options: options)
  }

  /// Starts running a workstation so that users can connect to it.
  ///
  /// @Snippet(path: "Workstations_StartWorkstation")
  public func startWorkstation(
    withPolling: StartWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Workstation(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.startWorkstation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Stops running a workstation, reducing costs.
  ///
  /// @Snippet(path: "Workstations_StopWorkstation")
  public func stopWorkstation(
    request: StopWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.stopWorkstation(request: request, options: options)
  }

  /// Stops running a workstation, reducing costs.
  ///
  /// @Snippet(path: "Workstations_StopWorkstation")
  public func stopWorkstation(
    withPolling: StopWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Workstation(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.stopWorkstation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Returns a short-lived credential that can be used to send authenticated and
  /// authorized traffic to a workstation.
  /// Once generated this token cannot be revoked and is good for the lifetime
  /// of the token.
  ///
  /// @Snippet(path: "Workstations_GenerateAccessToken")
  public func generateAccessToken(
    request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse {
    try await self.inner.generateAccessToken(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "Workstations_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "Workstations_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "Workstations_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workstations_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workstations_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workstations_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workstations_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Workstations_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `WorkstationsClient`.
  ///
  /// To mock `WorkstationsClient` change your functions to receive
  /// `some WorkstationsProtocol` or `any WorkstationsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol WorkstationsProtocol {
    /// See `WorkstationsClient.getWorkstationCluster`.
    func getWorkstationCluster(request: GetWorkstationClusterRequest) async throws
      -> GoogleCloudWorkstationsV1.WorkstationCluster

    /// See `WorkstationsClient.getWorkstationCluster`.
    func getWorkstationCluster(
      name: Swift.String,
    ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster

    /// See `WorkstationsClient.listWorkstationClusters`.
    func listWorkstationClusters(request: ListWorkstationClustersRequest) async throws
      -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse

    /// See `WorkstationsClient.listWorkstationClusters`.
    func listWorkstationClusters(
      byItem: ListWorkstationClustersRequest
    ) throws -> any AsyncSequence<WorkstationCluster, Swift.Error>

    /// See `WorkstationsClient.listWorkstationClusters`.
    func listWorkstationClusters(
      parent: Swift.String,
    ) throws -> any AsyncSequence<WorkstationCluster, Swift.Error>

    /// See `WorkstationsClient.createWorkstationCluster`.
    func createWorkstationCluster(request: CreateWorkstationClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.createWorkstationCluster`.
    func createWorkstationCluster(withPolling: CreateWorkstationClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.createWorkstationCluster`.
    func createWorkstationCluster(
      parent: Swift.String,
      workstationCluster: WorkstationCluster?,
      workstationClusterId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.updateWorkstationCluster`.
    func updateWorkstationCluster(request: UpdateWorkstationClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.updateWorkstationCluster`.
    func updateWorkstationCluster(withPolling: UpdateWorkstationClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.updateWorkstationCluster`.
    func updateWorkstationCluster(
      workstationCluster: WorkstationCluster?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.deleteWorkstationCluster`.
    func deleteWorkstationCluster(request: DeleteWorkstationClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.deleteWorkstationCluster`.
    func deleteWorkstationCluster(withPolling: DeleteWorkstationClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.deleteWorkstationCluster`.
    func deleteWorkstationCluster(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.getWorkstationConfig`.
    func getWorkstationConfig(request: GetWorkstationConfigRequest) async throws
      -> GoogleCloudWorkstationsV1.WorkstationConfig

    /// See `WorkstationsClient.getWorkstationConfig`.
    func getWorkstationConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig

    /// See `WorkstationsClient.listWorkstationConfigs`.
    func listWorkstationConfigs(request: ListWorkstationConfigsRequest) async throws
      -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse

    /// See `WorkstationsClient.listWorkstationConfigs`.
    func listWorkstationConfigs(
      byItem: ListWorkstationConfigsRequest
    ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error>

    /// See `WorkstationsClient.listWorkstationConfigs`.
    func listWorkstationConfigs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error>

    /// See `WorkstationsClient.listUsableWorkstationConfigs`.
    func listUsableWorkstationConfigs(request: ListUsableWorkstationConfigsRequest) async throws
      -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse

    /// See `WorkstationsClient.listUsableWorkstationConfigs`.
    func listUsableWorkstationConfigs(
      byItem: ListUsableWorkstationConfigsRequest
    ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error>

    /// See `WorkstationsClient.listUsableWorkstationConfigs`.
    func listUsableWorkstationConfigs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error>

    /// See `WorkstationsClient.createWorkstationConfig`.
    func createWorkstationConfig(request: CreateWorkstationConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.createWorkstationConfig`.
    func createWorkstationConfig(withPolling: CreateWorkstationConfigRequest) async throws
      -> any GoogleCloudGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.createWorkstationConfig`.
    func createWorkstationConfig(
      parent: Swift.String,
      workstationConfig: WorkstationConfig?,
      workstationConfigId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.updateWorkstationConfig`.
    func updateWorkstationConfig(request: UpdateWorkstationConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.updateWorkstationConfig`.
    func updateWorkstationConfig(withPolling: UpdateWorkstationConfigRequest) async throws
      -> any GoogleCloudGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.updateWorkstationConfig`.
    func updateWorkstationConfig(
      workstationConfig: WorkstationConfig?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.deleteWorkstationConfig`.
    func deleteWorkstationConfig(request: DeleteWorkstationConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.deleteWorkstationConfig`.
    func deleteWorkstationConfig(withPolling: DeleteWorkstationConfigRequest) async throws
      -> any GoogleCloudGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.deleteWorkstationConfig`.
    func deleteWorkstationConfig(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.getWorkstation`.
    func getWorkstation(request: GetWorkstationRequest) async throws
      -> GoogleCloudWorkstationsV1.Workstation

    /// See `WorkstationsClient.getWorkstation`.
    func getWorkstation(
      name: Swift.String,
    ) async throws -> GoogleCloudWorkstationsV1.Workstation

    /// See `WorkstationsClient.listWorkstations`.
    func listWorkstations(request: ListWorkstationsRequest) async throws
      -> GoogleCloudWorkstationsV1.ListWorkstationsResponse

    /// See `WorkstationsClient.listWorkstations`.
    func listWorkstations(
      byItem: ListWorkstationsRequest
    ) throws -> any AsyncSequence<Workstation, Swift.Error>

    /// See `WorkstationsClient.listWorkstations`.
    func listWorkstations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Workstation, Swift.Error>

    /// See `WorkstationsClient.listUsableWorkstations`.
    func listUsableWorkstations(request: ListUsableWorkstationsRequest) async throws
      -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse

    /// See `WorkstationsClient.listUsableWorkstations`.
    func listUsableWorkstations(
      byItem: ListUsableWorkstationsRequest
    ) throws -> any AsyncSequence<Workstation, Swift.Error>

    /// See `WorkstationsClient.listUsableWorkstations`.
    func listUsableWorkstations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Workstation, Swift.Error>

    /// See `WorkstationsClient.createWorkstation`.
    func createWorkstation(request: CreateWorkstationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.createWorkstation`.
    func createWorkstation(withPolling: CreateWorkstationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Workstation>

    /// See `WorkstationsClient.createWorkstation`.
    func createWorkstation(
      parent: Swift.String,
      workstation: Workstation?,
      workstationId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.updateWorkstation`.
    func updateWorkstation(request: UpdateWorkstationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.updateWorkstation`.
    func updateWorkstation(withPolling: UpdateWorkstationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Workstation>

    /// See `WorkstationsClient.updateWorkstation`.
    func updateWorkstation(
      workstation: Workstation?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.deleteWorkstation`.
    func deleteWorkstation(request: DeleteWorkstationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.deleteWorkstation`.
    func deleteWorkstation(withPolling: DeleteWorkstationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Workstation>

    /// See `WorkstationsClient.deleteWorkstation`.
    func deleteWorkstation(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.startWorkstation`.
    func startWorkstation(request: StartWorkstationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.startWorkstation`.
    func startWorkstation(withPolling: StartWorkstationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Workstation>

    /// See `WorkstationsClient.startWorkstation`.
    func startWorkstation(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.stopWorkstation`.
    func stopWorkstation(request: StopWorkstationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.stopWorkstation`.
    func stopWorkstation(withPolling: StopWorkstationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Workstation>

    /// See `WorkstationsClient.stopWorkstation`.
    func stopWorkstation(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.generateAccessToken`.
    func generateAccessToken(request: GenerateAccessTokenRequest) async throws
      -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse

    /// See `WorkstationsClient.generateAccessToken`.
    func generateAccessToken(
      workstation: Swift.String,
    ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse

    /// See `WorkstationsClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `WorkstationsClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `WorkstationsClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `WorkstationsClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `WorkstationsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `WorkstationsClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `WorkstationsClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `WorkstationsClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `WorkstationsClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `WorkstationsClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `WorkstationsClient.getWorkstationCluster`.
    func getWorkstationCluster(
      request: GetWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster

    /// See `WorkstationsClient.listWorkstationClusters`.
    func listWorkstationClusters(
      request: ListWorkstationClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse

    /// See `WorkstationsClient.listWorkstationClusters`.
    func listWorkstationClusters(
      byItem: ListWorkstationClustersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<WorkstationCluster, Swift.Error>

    /// See `WorkstationsClient.createWorkstationCluster`.
    func createWorkstationCluster(
      request: CreateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.createWorkstationCluster`.
    func createWorkstationCluster(
      withPolling: CreateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.updateWorkstationCluster`.
    func updateWorkstationCluster(
      request: UpdateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.updateWorkstationCluster`.
    func updateWorkstationCluster(
      withPolling: UpdateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.deleteWorkstationCluster`.
    func deleteWorkstationCluster(
      request: DeleteWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.deleteWorkstationCluster`.
    func deleteWorkstationCluster(
      withPolling: DeleteWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.getWorkstationConfig`.
    func getWorkstationConfig(
      request: GetWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig

    /// See `WorkstationsClient.listWorkstationConfigs`.
    func listWorkstationConfigs(
      request: ListWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse

    /// See `WorkstationsClient.listWorkstationConfigs`.
    func listWorkstationConfigs(
      byItem: ListWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error>

    /// See `WorkstationsClient.listUsableWorkstationConfigs`.
    func listUsableWorkstationConfigs(
      request: ListUsableWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse

    /// See `WorkstationsClient.listUsableWorkstationConfigs`.
    func listUsableWorkstationConfigs(
      byItem: ListUsableWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error>

    /// See `WorkstationsClient.createWorkstationConfig`.
    func createWorkstationConfig(
      request: CreateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.createWorkstationConfig`.
    func createWorkstationConfig(
      withPolling: CreateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.updateWorkstationConfig`.
    func updateWorkstationConfig(
      request: UpdateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.updateWorkstationConfig`.
    func updateWorkstationConfig(
      withPolling: UpdateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.deleteWorkstationConfig`.
    func deleteWorkstationConfig(
      request: DeleteWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.deleteWorkstationConfig`.
    func deleteWorkstationConfig(
      withPolling: DeleteWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.getWorkstation`.
    func getWorkstation(
      request: GetWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.Workstation

    /// See `WorkstationsClient.listWorkstations`.
    func listWorkstations(
      request: ListWorkstationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationsResponse

    /// See `WorkstationsClient.listWorkstations`.
    func listWorkstations(
      byItem: ListWorkstationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Workstation, Swift.Error>

    /// See `WorkstationsClient.listUsableWorkstations`.
    func listUsableWorkstations(
      request: ListUsableWorkstationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse

    /// See `WorkstationsClient.listUsableWorkstations`.
    func listUsableWorkstations(
      byItem: ListUsableWorkstationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Workstation, Swift.Error>

    /// See `WorkstationsClient.createWorkstation`.
    func createWorkstation(
      request: CreateWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.createWorkstation`.
    func createWorkstation(
      withPolling: CreateWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.updateWorkstation`.
    func updateWorkstation(
      request: UpdateWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.updateWorkstation`.
    func updateWorkstation(
      withPolling: UpdateWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.deleteWorkstation`.
    func deleteWorkstation(
      request: DeleteWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.deleteWorkstation`.
    func deleteWorkstation(
      withPolling: DeleteWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.startWorkstation`.
    func startWorkstation(
      request: StartWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.startWorkstation`.
    func startWorkstation(
      withPolling: StartWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.stopWorkstation`.
    func stopWorkstation(
      request: StopWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.stopWorkstation`.
    func stopWorkstation(
      withPolling: StopWorkstationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.generateAccessToken`.
    func generateAccessToken(
      request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse

    /// See `WorkstationsClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `WorkstationsClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `WorkstationsClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `WorkstationsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `WorkstationsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `WorkstationsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `WorkstationsClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.WorkstationsProtocol {
  public func getWorkstationCluster(request: GetWorkstationClusterRequest) async throws
    -> GoogleCloudWorkstationsV1.WorkstationCluster
  {
    try await self.getWorkstationCluster(request: request, options: .init())
  }

  public func getWorkstationCluster(
    request: GetWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getWorkstationCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster {
    let request = GetWorkstationClusterRequest().with {
      $0.name = name
    }
    return try await self.getWorkstationCluster(request: request)
  }

  public func listWorkstationClusters(request: ListWorkstationClustersRequest) async throws
    -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse
  {
    try await self.listWorkstationClusters(request: request, options: .init())
  }

  public func listWorkstationClusters(
    request: ListWorkstationClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkstationClusters(
    byItem: ListWorkstationClustersRequest
  ) throws -> any AsyncSequence<WorkstationCluster, Swift.Error> {
    try self.listWorkstationClusters(byItem: byItem, options: .init())
  }

  public func listWorkstationClusters(
    byItem: ListWorkstationClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<WorkstationCluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkstationClusters(
    parent: Swift.String,
  ) throws -> any AsyncSequence<WorkstationCluster, Swift.Error> {
    let request = ListWorkstationClustersRequest().with {
      $0.parent = parent
    }
    return try self.listWorkstationClusters(byItem: request)
  }

  public func createWorkstationCluster(request: CreateWorkstationClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createWorkstationCluster(request: request, options: .init())
  }

  public func createWorkstationCluster(
    request: CreateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createWorkstationCluster(withPolling: CreateWorkstationClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<WorkstationCluster>
  {
    try await self.createWorkstationCluster(withPolling: withPolling, options: .init())
  }

  public func createWorkstationCluster(
    withPolling: CreateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createWorkstationCluster(
    parent: Swift.String,
    workstationCluster: WorkstationCluster?,
    workstationClusterId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster> {
    let request = CreateWorkstationClusterRequest().with {
      $0.parent = parent
      $0.workstationCluster = workstationCluster
      $0.workstationClusterId = workstationClusterId
    }
    return try await self.createWorkstationCluster(withPolling: request)
  }

  public func updateWorkstationCluster(request: UpdateWorkstationClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateWorkstationCluster(request: request, options: .init())
  }

  public func updateWorkstationCluster(
    request: UpdateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateWorkstationCluster(withPolling: UpdateWorkstationClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<WorkstationCluster>
  {
    try await self.updateWorkstationCluster(withPolling: withPolling, options: .init())
  }

  public func updateWorkstationCluster(
    withPolling: UpdateWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkstationCluster(
    workstationCluster: WorkstationCluster?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster> {
    let request = UpdateWorkstationClusterRequest().with {
      $0.workstationCluster = workstationCluster
      $0.updateMask = updateMask
    }
    return try await self.updateWorkstationCluster(withPolling: request)
  }

  public func deleteWorkstationCluster(request: DeleteWorkstationClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteWorkstationCluster(request: request, options: .init())
  }

  public func deleteWorkstationCluster(
    request: DeleteWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteWorkstationCluster(withPolling: DeleteWorkstationClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<WorkstationCluster>
  {
    try await self.deleteWorkstationCluster(withPolling: withPolling, options: .init())
  }

  public func deleteWorkstationCluster(
    withPolling: DeleteWorkstationClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkstationCluster(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationCluster> {
    let request = DeleteWorkstationClusterRequest().with {
      $0.name = name
    }
    return try await self.deleteWorkstationCluster(withPolling: request)
  }

  public func getWorkstationConfig(request: GetWorkstationConfigRequest) async throws
    -> GoogleCloudWorkstationsV1.WorkstationConfig
  {
    try await self.getWorkstationConfig(request: request, options: .init())
  }

  public func getWorkstationConfig(
    request: GetWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getWorkstationConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig {
    let request = GetWorkstationConfigRequest().with {
      $0.name = name
    }
    return try await self.getWorkstationConfig(request: request)
  }

  public func listWorkstationConfigs(request: ListWorkstationConfigsRequest) async throws
    -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse
  {
    try await self.listWorkstationConfigs(request: request, options: .init())
  }

  public func listWorkstationConfigs(
    request: ListWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkstationConfigs(
    byItem: ListWorkstationConfigsRequest
  ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error> {
    try self.listWorkstationConfigs(byItem: byItem, options: .init())
  }

  public func listWorkstationConfigs(
    byItem: ListWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkstationConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error> {
    let request = ListWorkstationConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listWorkstationConfigs(byItem: request)
  }

  public func listUsableWorkstationConfigs(request: ListUsableWorkstationConfigsRequest)
    async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse
  {
    try await self.listUsableWorkstationConfigs(request: request, options: .init())
  }

  public func listUsableWorkstationConfigs(
    request: ListUsableWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listUsableWorkstationConfigs(
    byItem: ListUsableWorkstationConfigsRequest
  ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error> {
    try self.listUsableWorkstationConfigs(byItem: byItem, options: .init())
  }

  public func listUsableWorkstationConfigs(
    byItem: ListUsableWorkstationConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listUsableWorkstationConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<WorkstationConfig, Swift.Error> {
    let request = ListUsableWorkstationConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listUsableWorkstationConfigs(byItem: request)
  }

  public func createWorkstationConfig(request: CreateWorkstationConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createWorkstationConfig(request: request, options: .init())
  }

  public func createWorkstationConfig(
    request: CreateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createWorkstationConfig(withPolling: CreateWorkstationConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<WorkstationConfig>
  {
    try await self.createWorkstationConfig(withPolling: withPolling, options: .init())
  }

  public func createWorkstationConfig(
    withPolling: CreateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createWorkstationConfig(
    parent: Swift.String,
    workstationConfig: WorkstationConfig?,
    workstationConfigId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig> {
    let request = CreateWorkstationConfigRequest().with {
      $0.parent = parent
      $0.workstationConfig = workstationConfig
      $0.workstationConfigId = workstationConfigId
    }
    return try await self.createWorkstationConfig(withPolling: request)
  }

  public func updateWorkstationConfig(request: UpdateWorkstationConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateWorkstationConfig(request: request, options: .init())
  }

  public func updateWorkstationConfig(
    request: UpdateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateWorkstationConfig(withPolling: UpdateWorkstationConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<WorkstationConfig>
  {
    try await self.updateWorkstationConfig(withPolling: withPolling, options: .init())
  }

  public func updateWorkstationConfig(
    withPolling: UpdateWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkstationConfig(
    workstationConfig: WorkstationConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig> {
    let request = UpdateWorkstationConfigRequest().with {
      $0.workstationConfig = workstationConfig
      $0.updateMask = updateMask
    }
    return try await self.updateWorkstationConfig(withPolling: request)
  }

  public func deleteWorkstationConfig(request: DeleteWorkstationConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteWorkstationConfig(request: request, options: .init())
  }

  public func deleteWorkstationConfig(
    request: DeleteWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteWorkstationConfig(withPolling: DeleteWorkstationConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<WorkstationConfig>
  {
    try await self.deleteWorkstationConfig(withPolling: withPolling, options: .init())
  }

  public func deleteWorkstationConfig(
    withPolling: DeleteWorkstationConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<WorkstationConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkstationConfig(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<WorkstationConfig> {
    let request = DeleteWorkstationConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteWorkstationConfig(withPolling: request)
  }

  public func getWorkstation(request: GetWorkstationRequest) async throws
    -> GoogleCloudWorkstationsV1.Workstation
  {
    try await self.getWorkstation(request: request, options: .init())
  }

  public func getWorkstation(
    request: GetWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.Workstation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getWorkstation(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkstationsV1.Workstation {
    let request = GetWorkstationRequest().with {
      $0.name = name
    }
    return try await self.getWorkstation(request: request)
  }

  public func listWorkstations(request: ListWorkstationsRequest) async throws
    -> GoogleCloudWorkstationsV1.ListWorkstationsResponse
  {
    try await self.listWorkstations(request: request, options: .init())
  }

  public func listWorkstations(
    request: ListWorkstationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkstations(
    byItem: ListWorkstationsRequest
  ) throws -> any AsyncSequence<Workstation, Swift.Error> {
    try self.listWorkstations(byItem: byItem, options: .init())
  }

  public func listWorkstations(
    byItem: ListWorkstationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workstation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkstationsV1.ListWorkstationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkstations(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Workstation, Swift.Error> {
    let request = ListWorkstationsRequest().with {
      $0.parent = parent
    }
    return try self.listWorkstations(byItem: request)
  }

  public func listUsableWorkstations(request: ListUsableWorkstationsRequest) async throws
    -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse
  {
    try await self.listUsableWorkstations(request: request, options: .init())
  }

  public func listUsableWorkstations(
    request: ListUsableWorkstationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listUsableWorkstations(
    byItem: ListUsableWorkstationsRequest
  ) throws -> any AsyncSequence<Workstation, Swift.Error> {
    try self.listUsableWorkstations(byItem: byItem, options: .init())
  }

  public func listUsableWorkstations(
    byItem: ListUsableWorkstationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workstation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listUsableWorkstations(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Workstation, Swift.Error> {
    let request = ListUsableWorkstationsRequest().with {
      $0.parent = parent
    }
    return try self.listUsableWorkstations(byItem: request)
  }

  public func createWorkstation(request: CreateWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createWorkstation(request: request, options: .init())
  }

  public func createWorkstation(
    request: CreateWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createWorkstation(withPolling: CreateWorkstationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Workstation>
  {
    try await self.createWorkstation(withPolling: withPolling, options: .init())
  }

  public func createWorkstation(
    withPolling: CreateWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createWorkstation(
    parent: Swift.String,
    workstation: Workstation?,
    workstationId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let request = CreateWorkstationRequest().with {
      $0.parent = parent
      $0.workstation = workstation
      $0.workstationId = workstationId
    }
    return try await self.createWorkstation(withPolling: request)
  }

  public func updateWorkstation(request: UpdateWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateWorkstation(request: request, options: .init())
  }

  public func updateWorkstation(
    request: UpdateWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateWorkstation(withPolling: UpdateWorkstationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Workstation>
  {
    try await self.updateWorkstation(withPolling: withPolling, options: .init())
  }

  public func updateWorkstation(
    withPolling: UpdateWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkstation(
    workstation: Workstation?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let request = UpdateWorkstationRequest().with {
      $0.workstation = workstation
      $0.updateMask = updateMask
    }
    return try await self.updateWorkstation(withPolling: request)
  }

  public func deleteWorkstation(request: DeleteWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteWorkstation(request: request, options: .init())
  }

  public func deleteWorkstation(
    request: DeleteWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteWorkstation(withPolling: DeleteWorkstationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Workstation>
  {
    try await self.deleteWorkstation(withPolling: withPolling, options: .init())
  }

  public func deleteWorkstation(
    withPolling: DeleteWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkstation(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let request = DeleteWorkstationRequest().with {
      $0.name = name
    }
    return try await self.deleteWorkstation(withPolling: request)
  }

  public func startWorkstation(request: StartWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.startWorkstation(request: request, options: .init())
  }

  public func startWorkstation(
    request: StartWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func startWorkstation(withPolling: StartWorkstationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Workstation>
  {
    try await self.startWorkstation(withPolling: withPolling, options: .init())
  }

  public func startWorkstation(
    withPolling: StartWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func startWorkstation(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let request = StartWorkstationRequest().with {
      $0.name = name
    }
    return try await self.startWorkstation(withPolling: request)
  }

  public func stopWorkstation(request: StopWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.stopWorkstation(request: request, options: .init())
  }

  public func stopWorkstation(
    request: StopWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func stopWorkstation(withPolling: StopWorkstationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Workstation>
  {
    try await self.stopWorkstation(withPolling: withPolling, options: .init())
  }

  public func stopWorkstation(
    withPolling: StopWorkstationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Workstation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func stopWorkstation(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Workstation> {
    let request = StopWorkstationRequest().with {
      $0.name = name
    }
    return try await self.stopWorkstation(withPolling: request)
  }

  public func generateAccessToken(request: GenerateAccessTokenRequest) async throws
    -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse
  {
    try await self.generateAccessToken(request: request, options: .init())
  }

  public func generateAccessToken(
    request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateAccessToken(
    workstation: Swift.String,
  ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse {
    let request = GenerateAccessTokenRequest().with {
      $0.workstation = workstation
    }
    return try await self.generateAccessToken(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
