// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A single instance of a developer workstation with its own persistent storage.
public struct Workstation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Full name of this workstation.
  public var name: Swift.String = Swift.String()

  /// Optional. Human-readable name for this workstation.
  public var displayName: Swift.String = Swift.String()

  /// Output only. A system-assigned unique identifier for this workstation.
  public var uid: Swift.String = Swift.String()

  /// Output only. Indicates whether this workstation is currently being updated
  /// to match its intended state.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. Client-specified annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional.
  /// [Labels](https://cloud.google.com/workstations/docs/label-resources) that
  /// are applied to the workstation and that are also propagated to the
  /// underlying Compute Engine resources.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Time when this workstation was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when this workstation was most recently updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when this workstation was most recently successfully
  /// started, regardless of the workstation's initial state.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when this workstation was soft-deleted.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Checksum computed by the server. May be sent on update and delete
  /// requests to make sure that the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. Directories to persist across workstation sessions.
  public var persistentDirectories: [Workstation.WorkstationPersistentDirectory] = []

  /// Output only. Current state of the workstation.
  public var state: Workstation.State = Workstation.State()

  /// Output only. Host to which clients can send HTTPS traffic that will be
  /// received by the workstation. Authorized traffic will be received to the
  /// workstation as HTTP on port 80. To send traffic to a different port,
  /// clients may prefix the host with the destination port in the format
  /// `{port}-{host}`.
  public var host: Swift.String = Swift.String()

  /// Optional. Environment variables passed to the workstation container's
  /// entrypoint.
  public var env: [Swift.String: Swift.String] = [:]

  /// Output only. The name of the Google Cloud KMS encryption key used to
  /// encrypt this workstation. The KMS key can only be configured in the
  /// WorkstationConfig. The expected format is
  /// `projects/*/locations/*/keyRings/*/cryptoKeys/*`.
  public var kmsKey: Swift.String = Swift.String()

  /// Optional. The source workstation from which this workstation's persistent
  /// directories were cloned on creation.
  public var sourceWorkstation: Swift.String = Swift.String()

  /// Optional. Output only. Runtime host for the workstation when in
  /// STATE_RUNNING.
  public var runtimeHost: Workstation.RuntimeHost? = nil

  /// Initialize a new instance of `Workstation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Workstation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A directory to persist across workstation sessions. Updates to this field
  /// will only take effect on this workstation after it is restarted.
  public struct WorkstationPersistentDirectory: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The mount path of the persistent directory.
    public var mountPath: Swift.String = Swift.String()

    /// Optional. Size of the persistent directory in GB. If specified in an
    /// update request, this is the desired size of the directory.
    public var sizeGb: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `WorkstationPersistentDirectory`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WorkstationPersistentDirectory().with { $0.mountPath = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.workstations.v1.Workstation.WorkstationPersistentDirectory"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Runtime host for the workstation.
  public struct RuntimeHost: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Type of host used by the workstation.
    public var hostType: OneOf_HostType? = nil

    /// Initialize a new instance of `RuntimeHost`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RuntimeHost().with { $0.gceInstanceHost = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case gceInstanceHost = "gceInstanceHost"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var hostType: OneOf_HostType? = nil
      let hostTypeCheckAndSet = {
        if hostType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'hostType'"))
        }
        hostType = $0
      }
      if let gceInstanceHost = try container.decodeIfPresent(
        Workstation.RuntimeHost.GceInstanceHost?.self, forKey: .gceInstanceHost)
      {
        try hostTypeCheckAndSet(.gceInstanceHost(gceInstanceHost))
      }
      self.hostType = hostType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.hostType {
        switch choice {
        case .gceInstanceHost(let value):
          try container.encode(value, forKey: .gceInstanceHost)
        }
      }
    }

    /// The Compute Engine instance host.
    public struct GceInstanceHost: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional. Output only. The name of the Compute Engine instance.
      public var name: Swift.String = Swift.String()

      /// Optional. Output only. The ID of the Compute Engine instance.
      public var id: Swift.String = Swift.String()

      /// Optional. Output only. The zone of the Compute Engine instance.
      public var zone: Swift.String = Swift.String()

      /// Initialize a new instance of `GceInstanceHost`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GceInstanceHost().with { $0.name = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.workstations.v1.Workstation.RuntimeHost.GceInstanceHost"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Type of host used by the workstation.
    public enum OneOf_HostType: Codable, Equatable, Sendable {
      /// Specifies a Compute Engine instance as the host.
      indirect case gceInstanceHost(Workstation.RuntimeHost.GceInstanceHost?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.Workstation.RuntimeHost"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Whether a workstation is running and ready to receive user requests.
  public enum State: Codable, Equatable, Sendable {
    /// Do not use.
    case unspecified
    /// The workstation is not yet ready to accept requests from users but will
    /// be soon.
    case starting
    /// The workstation is ready to accept requests from users.
    case running
    /// The workstation is being stopped.
    case stopping
    /// The workstation is stopped and will not be able to receive requests until
    /// it is started.
    case stopped
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .starting: return 1
      case .running: return 2
      case .stopping: return 3
      case .stopped: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .starting: return "STATE_STARTING"
      case .running: return "STATE_RUNNING"
      case .stopping: return "STATE_STOPPING"
      case .stopped: return "STATE_STOPPED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "STATE_STARTING": self = .starting
      case "STATE_RUNNING": self = .running
      case "STATE_STOPPING": self = .stopping
      case "STATE_STOPPED": self = .stopped
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .starting
      case 2: self = .running
      case 3: self = .stopping
      case 4: self = .stopped
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .starting: return try container.encode(1)
      case .running: return try container.encode(2)
      case .stopping: return try container.encode(3)
      case .stopped: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workstations.v1.Workstation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
