// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class WorkstationsRetry: WorkstationsStub {
    let inner: any WorkstationsStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any WorkstationsStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getWorkstationCluster(
      request: GetWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetWorkstationClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudWorkstationsV1.WorkstationCluster
          in
          return try await self.inner.getWorkstationCluster(request: r, options: o)
        })
    }

    public func listWorkstationClusters(
      request: ListWorkstationClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListWorkstationClustersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse
          in
          return try await self.inner.listWorkstationClusters(request: r, options: o)
        })
    }

    public func createWorkstationCluster(
      request: CreateWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateWorkstationClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createWorkstationCluster(request: r, options: o)
        })
    }

    public func updateWorkstationCluster(
      request: UpdateWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateWorkstationClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateWorkstationCluster(request: r, options: o)
        })
    }

    public func deleteWorkstationCluster(
      request: DeleteWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteWorkstationClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteWorkstationCluster(request: r, options: o)
        })
    }

    public func getWorkstationConfig(
      request: GetWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetWorkstationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudWorkstationsV1.WorkstationConfig
          in
          return try await self.inner.getWorkstationConfig(request: r, options: o)
        })
    }

    public func listWorkstationConfigs(
      request: ListWorkstationConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListWorkstationConfigsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse
          in
          return try await self.inner.listWorkstationConfigs(request: r, options: o)
        })
    }

    public func listUsableWorkstationConfigs(
      request: ListUsableWorkstationConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListUsableWorkstationConfigsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse
          in
          return try await self.inner.listUsableWorkstationConfigs(request: r, options: o)
        })
    }

    public func createWorkstationConfig(
      request: CreateWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateWorkstationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createWorkstationConfig(request: r, options: o)
        })
    }

    public func updateWorkstationConfig(
      request: UpdateWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateWorkstationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateWorkstationConfig(request: r, options: o)
        })
    }

    public func deleteWorkstationConfig(
      request: DeleteWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteWorkstationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteWorkstationConfig(request: r, options: o)
        })
    }

    public func getWorkstation(
      request: GetWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.Workstation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetWorkstationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudWorkstationsV1.Workstation
          in
          return try await self.inner.getWorkstation(request: r, options: o)
        })
    }

    public func listWorkstations(
      request: ListWorkstationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListWorkstationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudWorkstationsV1.ListWorkstationsResponse
          in
          return try await self.inner.listWorkstations(request: r, options: o)
        })
    }

    public func listUsableWorkstations(
      request: ListUsableWorkstationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListUsableWorkstationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse
          in
          return try await self.inner.listUsableWorkstations(request: r, options: o)
        })
    }

    public func createWorkstation(
      request: CreateWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateWorkstationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createWorkstation(request: r, options: o)
        })
    }

    public func updateWorkstation(
      request: UpdateWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateWorkstationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateWorkstation(request: r, options: o)
        })
    }

    public func deleteWorkstation(
      request: DeleteWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteWorkstationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteWorkstation(request: r, options: o)
        })
    }

    public func startWorkstation(
      request: StartWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StartWorkstationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startWorkstation(request: r, options: o)
        })
    }

    public func stopWorkstation(
      request: StopWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StopWorkstationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.stopWorkstation(request: r, options: o)
        })
    }

    public func generateAccessToken(
      request: GenerateAccessTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GenerateAccessTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse
          in
          return try await self.inner.generateAccessToken(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
