// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// A workstation cluster resource in the Cloud Workstations API.
///
/// Defines a group of workstations in a particular region and the
/// VPC network they're attached to.
public struct WorkstationCluster: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Full name of this workstation cluster.
  public var name: Swift.String = Swift.String()

  /// Optional. Human-readable name for this workstation cluster.
  public var displayName: Swift.String = Swift.String()

  /// Output only. A system-assigned unique identifier for this workstation
  /// cluster.
  public var uid: Swift.String = Swift.String()

  /// Output only. Indicates whether this workstation cluster is currently being
  /// updated to match its intended state.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. Client-specified annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional.
  /// [Labels](https://cloud.google.com/workstations/docs/label-resources) that
  /// are applied to the workstation cluster and that are also propagated to the
  /// underlying Compute Engine resources.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Time when this workstation cluster was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when this workstation cluster was most recently updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when this workstation cluster was soft-deleted.
  public var deleteTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Checksum computed by the server. May be sent on update and delete
  /// requests to make sure that the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String = Swift.String()

  /// Immutable. Name of the Compute Engine network in which instances associated
  /// with this workstation cluster will be created.
  public var network: Swift.String = Swift.String()

  /// Immutable. Name of the Compute Engine subnetwork in which instances
  /// associated with this workstation cluster will be created. Must be part of
  /// the subnetwork specified for this workstation cluster.
  public var subnetwork: Swift.String = Swift.String()

  /// Output only. The private IP address of the control plane for this
  /// workstation cluster. Workstation VMs need access to this IP address to work
  /// with the service, so make sure that your firewall rules allow egress from
  /// the workstation VMs to this address.
  public var controlPlaneIp: Swift.String = Swift.String()

  /// Optional. Configuration for private workstation cluster.
  public var privateClusterConfig: WorkstationCluster.PrivateClusterConfig? = nil

  /// Optional. Configuration options for a custom domain.
  public var domainConfig: WorkstationCluster.DomainConfig? = nil

  /// Output only. Whether this workstation cluster is in degraded mode, in which
  /// case it may require user action to restore full functionality. The
  /// [conditions][google.cloud.workstations.v1.WorkstationCluster.conditions]
  /// field contains detailed information about the status of the cluster.
  ///
  /// [google.cloud.workstations.v1.WorkstationCluster.conditions]: <doc:WorkstationCluster/conditions>
  public var degraded: Swift.Bool = Swift.Bool()

  /// Output only. Status conditions describing the workstation cluster's current
  /// state.
  public var conditions: [GoogleRpc.Status] = []

  /// Optional. Input only. Immutable. Tag keys/values directly bound to this
  /// resource. For example:
  ///   "123/environment": "production",
  ///   "123/costCenter": "marketing"
  public var tags: [Swift.String: Swift.String] = [:]

  /// Optional. Configuration options for Cluster HTTP Gateway.
  public var gatewayConfig: WorkstationCluster.GatewayConfig? = nil

  /// Optional. Specifies the redirect URL for unauthorized requests received by
  /// workstation VMs in this cluster.
  ///
  /// Redirects to this endpoint will send a base64 encoded `state` query param
  /// containing the target workstation name and original request hostname. The
  /// endpoint is responsible for retrieving a token using `GenerateAccessToken`
  /// and redirecting back to the original hostname with the token.
  public var workstationAuthorizationUrl: Swift.String = Swift.String()

  /// Optional. Specifies the launch URL for workstations in this cluster.
  /// Requests sent to unstarted workstations will be redirected to this URL.
  ///
  /// Requests redirected to the launch endpoint will be sent with a
  /// `workstation` and `project` query parameter containing the full workstation
  /// resource name and project ID, respectively. The launch endpoint is
  /// responsible for starting the workstation, polling it until it reaches
  /// `STATE_RUNNING`, and then issuing a redirect to the workstation's host URL.
  public var workstationLaunchUrl: Swift.String = Swift.String()

  /// Initialize a new instance of `WorkstationCluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkstationCluster().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Configuration options for private workstation clusters.
  public struct PrivateClusterConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Immutable. Whether Workstations endpoint is private.
    public var enablePrivateEndpoint: Swift.Bool = Swift.Bool()

    /// Output only. Hostname for the workstation cluster. This field will be
    /// populated only when private endpoint is enabled. To access workstations
    /// in the workstation cluster, create a new DNS zone mapping this domain
    /// name to an internal IP address and a forwarding rule mapping that address
    /// to the service attachment.
    public var clusterHostname: Swift.String = Swift.String()

    /// Output only. Service attachment URI for the workstation cluster. The
    /// service attachment is created when private endpoint is enabled. To access
    /// workstations in the workstation cluster, configure access to the managed
    /// service using [Private Service
    /// Connect](https://cloud.google.com/vpc/docs/configure-private-service-connect-services).
    public var serviceAttachmentUri: Swift.String = Swift.String()

    /// Optional. Additional projects that are allowed to attach to the
    /// workstation cluster's service attachment. By default, the workstation
    /// cluster's project and the VPC host project (if different) are allowed.
    public var allowedProjects: [Swift.String] = []

    /// Initialize a new instance of `PrivateClusterConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PrivateClusterConfig().with { $0.enablePrivateEndpoint = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.workstations.v1.WorkstationCluster.PrivateClusterConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration options for a custom domain.
  public struct DomainConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Immutable. Domain used by Workstations for HTTP ingress.
    public var domain: Swift.String = Swift.String()

    /// Initialize a new instance of `DomainConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DomainConfig().with { $0.domain = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.WorkstationCluster.DomainConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration options for Cluster HTTP Gateway.
  public struct GatewayConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Whether HTTP/2 is enabled for this workstation cluster.
    /// Defaults to false.
    public var http2Enabled: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `GatewayConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GatewayConfig().with { $0.http2Enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.WorkstationCluster.GatewayConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workstations.v1.WorkstationCluster"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
