// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A workstation cluster resource in the Cloud Workstations API.
///
/// Defines a group of workstations in a particular region and the
/// VPC network they're attached to.
public struct WorkstationCluster: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Full name of this workstation cluster.
  public var name: Swift.String = Swift.String()

  /// Optional. Human-readable name for this workstation cluster.
  public var displayName: Swift.String = Swift.String()

  /// Output only. A system-assigned unique identifier for this workstation
  /// cluster.
  public var uid: Swift.String = Swift.String()

  /// Output only. Indicates whether this workstation cluster is currently being
  /// updated to match its intended state.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. Client-specified annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional.
  /// [Labels](https://cloud.google.com/workstations/docs/label-resources) that
  /// are applied to the workstation cluster and that are also propagated to the
  /// underlying Compute Engine resources.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Time when this workstation cluster was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Time when this workstation cluster was most recently updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. Time when this workstation cluster was soft-deleted.
  public var deleteTime: GoogleWKT.Timestamp? = nil

  /// Optional. Checksum computed by the server. May be sent on update and delete
  /// requests to make sure that the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String = Swift.String()

  /// Immutable. Name of the Compute Engine network in which instances associated
  /// with this workstation cluster will be created.
  public var network: Swift.String = Swift.String()

  /// Immutable. Name of the Compute Engine subnetwork in which instances
  /// associated with this workstation cluster will be created. Must be part of
  /// the subnetwork specified for this workstation cluster.
  public var subnetwork: Swift.String = Swift.String()

  /// Output only. The private IP address of the control plane for this
  /// workstation cluster. Workstation VMs need access to this IP address to work
  /// with the service, so make sure that your firewall rules allow egress from
  /// the workstation VMs to this address.
  public var controlPlaneIp: Swift.String = Swift.String()

  /// Optional. Configuration for private workstation cluster.
  public var privateClusterConfig: WorkstationCluster.PrivateClusterConfig? = nil

  /// Optional. Configuration options for a custom domain.
  public var domainConfig: WorkstationCluster.DomainConfig? = nil

  /// Output only. Whether this workstation cluster is in degraded mode, in which
  /// case it may require user action to restore full functionality. The
  /// [conditions][google.cloud.workstations.v1.WorkstationCluster.conditions]
  /// field contains detailed information about the status of the cluster.
  ///
  /// [google.cloud.workstations.v1.WorkstationCluster.conditions]: <doc:WorkstationCluster/conditions>
  public var degraded: Swift.Bool = Swift.Bool()

  /// Output only. Status conditions describing the workstation cluster's current
  /// state.
  public var conditions: [GoogleRpc.Status] = []

  /// Optional. Input only. Immutable. Tag keys/values directly bound to this
  /// resource. For example:
  ///   "123/environment": "production",
  ///   "123/costCenter": "marketing"
  public var tags: [Swift.String: Swift.String] = [:]

  /// Optional. Configuration options for Cluster HTTP Gateway.
  public var gatewayConfig: WorkstationCluster.GatewayConfig? = nil

  /// Optional. Specifies the redirect URL for unauthorized requests received by
  /// workstation VMs in this cluster.
  ///
  /// Redirects to this endpoint will send a base64 encoded `state` query param
  /// containing the target workstation name and original request hostname. The
  /// endpoint is responsible for retrieving a token using `GenerateAccessToken`
  /// and redirecting back to the original hostname with the token.
  public var workstationAuthorizationUrl: Swift.String = Swift.String()

  /// Optional. Specifies the launch URL for workstations in this cluster.
  /// Requests sent to unstarted workstations will be redirected to this URL.
  ///
  /// Requests redirected to the launch endpoint will be sent with a
  /// `workstation` and `project` query parameter containing the full workstation
  /// resource name and project ID, respectively. The launch endpoint is
  /// responsible for starting the workstation, polling it until it reaches
  /// `STATE_RUNNING`, and then issuing a redirect to the workstation's host URL.
  public var workstationLaunchUrl: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `WorkstationCluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkstationCluster().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let uid = CodingKeys(stringValue: "uid")
    static let reconciling = CodingKeys(stringValue: "reconciling")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let labels = CodingKeys(stringValue: "labels")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let etag = CodingKeys(stringValue: "etag")
    static let network = CodingKeys(stringValue: "network")
    static let subnetwork = CodingKeys(stringValue: "subnetwork")
    static let controlPlaneIp = CodingKeys(stringValue: "controlPlaneIp")
    static let privateClusterConfig = CodingKeys(stringValue: "privateClusterConfig")
    static let domainConfig = CodingKeys(stringValue: "domainConfig")
    static let degraded = CodingKeys(stringValue: "degraded")
    static let conditions = CodingKeys(stringValue: "conditions")
    static let tags = CodingKeys(stringValue: "tags")
    static let gatewayConfig = CodingKeys(stringValue: "gatewayConfig")
    static let workstationAuthorizationUrl = CodingKeys(stringValue: "workstationAuthorizationUrl")
    static let workstationLaunchUrl = CodingKeys(stringValue: "workstationLaunchUrl")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "uid",
      "reconciling",
      "annotations",
      "labels",
      "createTime",
      "updateTime",
      "deleteTime",
      "etag",
      "network",
      "subnetwork",
      "controlPlaneIp",
      "privateClusterConfig",
      "domainConfig",
      "degraded",
      "conditions",
      "tags",
      "gatewayConfig",
      "workstationAuthorizationUrl",
      "workstationLaunchUrl",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reconciling) {
      self.reconciling = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetwork) {
      self.subnetwork = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .controlPlaneIp) {
      self.controlPlaneIp = value
    }
    self.privateClusterConfig = try container.decodeIfPresent(
      WorkstationCluster.PrivateClusterConfig.self, forKey: .privateClusterConfig)
    self.domainConfig = try container.decodeIfPresent(
      WorkstationCluster.DomainConfig.self, forKey: .domainConfig)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .degraded) {
      self.degraded = value
    }
    if let value = try container.decodeIfPresent([GoogleRpc.Status].self, forKey: .conditions) {
      self.conditions = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    self.gatewayConfig = try container.decodeIfPresent(
      WorkstationCluster.GatewayConfig.self, forKey: .gatewayConfig)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .workstationAuthorizationUrl)
    {
      self.workstationAuthorizationUrl = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .workstationLaunchUrl) {
      self.workstationLaunchUrl = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.subnetwork, forKey: .subnetwork)
    try container.encode(self.controlPlaneIp, forKey: .controlPlaneIp)
    try container.encodeIfPresent(self.privateClusterConfig, forKey: .privateClusterConfig)
    try container.encodeIfPresent(self.domainConfig, forKey: .domainConfig)
    try container.encode(self.degraded, forKey: .degraded)
    try container.encode(self.conditions, forKey: .conditions)
    try container.encode(self.tags, forKey: .tags)
    try container.encodeIfPresent(self.gatewayConfig, forKey: .gatewayConfig)
    try container.encode(self.workstationAuthorizationUrl, forKey: .workstationAuthorizationUrl)
    try container.encode(self.workstationLaunchUrl, forKey: .workstationLaunchUrl)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration options for private workstation clusters.
  public struct PrivateClusterConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Immutable. Whether Workstations endpoint is private.
    public var enablePrivateEndpoint: Swift.Bool = Swift.Bool()

    /// Output only. Hostname for the workstation cluster. This field will be
    /// populated only when private endpoint is enabled. To access workstations
    /// in the workstation cluster, create a new DNS zone mapping this domain
    /// name to an internal IP address and a forwarding rule mapping that address
    /// to the service attachment.
    public var clusterHostname: Swift.String = Swift.String()

    /// Output only. Service attachment URI for the workstation cluster. The
    /// service attachment is created when private endpoint is enabled. To access
    /// workstations in the workstation cluster, configure access to the managed
    /// service using [Private Service
    /// Connect](https://cloud.google.com/vpc/docs/configure-private-service-connect-services).
    public var serviceAttachmentUri: Swift.String = Swift.String()

    /// Optional. Additional projects that are allowed to attach to the
    /// workstation cluster's service attachment. By default, the workstation
    /// cluster's project and the VPC host project (if different) are allowed.
    public var allowedProjects: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PrivateClusterConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PrivateClusterConfig().with { $0.enablePrivateEndpoint = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enablePrivateEndpoint = CodingKeys(stringValue: "enablePrivateEndpoint")
      static let clusterHostname = CodingKeys(stringValue: "clusterHostname")
      static let serviceAttachmentUri = CodingKeys(stringValue: "serviceAttachmentUri")
      static let allowedProjects = CodingKeys(stringValue: "allowedProjects")

      static let _knownKeys: Set<Swift.String> = [
        "enablePrivateEndpoint",
        "clusterHostname",
        "serviceAttachmentUri",
        "allowedProjects",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enablePrivateEndpoint)
      {
        self.enablePrivateEndpoint = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterHostname) {
        self.clusterHostname = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAttachmentUri)
      {
        self.serviceAttachmentUri = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .allowedProjects) {
        self.allowedProjects = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enablePrivateEndpoint, forKey: .enablePrivateEndpoint)
      try container.encode(self.clusterHostname, forKey: .clusterHostname)
      try container.encode(self.serviceAttachmentUri, forKey: .serviceAttachmentUri)
      try container.encode(self.allowedProjects, forKey: .allowedProjects)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.workstations.v1.WorkstationCluster.PrivateClusterConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration options for a custom domain.
  public struct DomainConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Immutable. Domain used by Workstations for HTTP ingress.
    public var domain: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DomainConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DomainConfig().with { $0.domain = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let domain = CodingKeys(stringValue: "domain")

      static let _knownKeys: Set<Swift.String> = [
        "domain"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .domain) {
        self.domain = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.domain, forKey: .domain)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.WorkstationCluster.DomainConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration options for Cluster HTTP Gateway.
  public struct GatewayConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Whether HTTP/2 is enabled for this workstation cluster.
    /// Defaults to false.
    public var http2Enabled: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GatewayConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GatewayConfig().with { $0.http2Enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let http2Enabled = CodingKeys(stringValue: "http2Enabled")

      static let _knownKeys: Set<Swift.String> = [
        "http2Enabled"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .http2Enabled) {
        self.http2Enabled = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.http2Enabled, forKey: .http2Enabled)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workstations.v1.WorkstationCluster.GatewayConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workstations.v1.WorkstationCluster"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
