// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for interacting with Cloud Workstations.
///
/// @Snippet(path: "WorkstationsQuickstart")
public final class WorkstationsClient: Clients.WorkstationsProtocol, Sendable {
  let inner: any Clients.WorkstationsStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `WorkstationsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.WorkstationsStub = try Clients.WorkstationsTransport(options)
    inner = Clients.WorkstationsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.WorkstationsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Returns the requested workstation cluster.
  ///
  /// @Snippet(path: "Workstations_GetWorkstationCluster")
  public func getWorkstationCluster(
    request: GetWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster {
    try await self.inner.getWorkstationCluster(request: request, options: options)
  }

  /// Returns all workstation clusters in the specified location.
  ///
  /// @Snippet(path: "Workstations_ListWorkstationClusters")
  public func listWorkstationClusters(
    request: ListWorkstationClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse {
    try await self.inner.listWorkstationClusters(request: request, options: options)
  }

  /// Creates a new workstation cluster.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstationCluster")
  public func createWorkstationCluster(
    request: CreateWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createWorkstationCluster(request: request, options: options)
  }

  /// Creates a new workstation cluster.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstationCluster")
  public func createWorkstationClusterPollingUntilDone(
    request: CreateWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<WorkstationCluster>.State in
      return try op._extractStatus(WorkstationCluster.self)
    }
    let rawOp = try await self.createWorkstationCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an existing workstation cluster.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstationCluster")
  public func updateWorkstationCluster(
    request: UpdateWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateWorkstationCluster(request: request, options: options)
  }

  /// Updates an existing workstation cluster.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstationCluster")
  public func updateWorkstationClusterPollingUntilDone(
    request: UpdateWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<WorkstationCluster>.State in
      return try op._extractStatus(WorkstationCluster.self)
    }
    let rawOp = try await self.updateWorkstationCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified workstation cluster.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstationCluster")
  public func deleteWorkstationCluster(
    request: DeleteWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteWorkstationCluster(request: request, options: options)
  }

  /// Deletes the specified workstation cluster.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstationCluster")
  public func deleteWorkstationClusterPollingUntilDone(
    request: DeleteWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<WorkstationCluster>.State in
      return try op._extractStatus(WorkstationCluster.self)
    }
    let rawOp = try await self.deleteWorkstationCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Returns the requested workstation configuration.
  ///
  /// @Snippet(path: "Workstations_GetWorkstationConfig")
  public func getWorkstationConfig(
    request: GetWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig {
    try await self.inner.getWorkstationConfig(request: request, options: options)
  }

  /// Returns all workstation configurations in the specified cluster.
  ///
  /// @Snippet(path: "Workstations_ListWorkstationConfigs")
  public func listWorkstationConfigs(
    request: ListWorkstationConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse {
    try await self.inner.listWorkstationConfigs(request: request, options: options)
  }

  /// Returns all workstation configurations in the specified cluster on which
  /// the caller has the "workstations.workstation.create" permission.
  ///
  /// @Snippet(path: "Workstations_ListUsableWorkstationConfigs")
  public func listUsableWorkstationConfigs(
    request: ListUsableWorkstationConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse {
    try await self.inner.listUsableWorkstationConfigs(request: request, options: options)
  }

  /// Creates a new workstation configuration.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstationConfig")
  public func createWorkstationConfig(
    request: CreateWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createWorkstationConfig(request: request, options: options)
  }

  /// Creates a new workstation configuration.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstationConfig")
  public func createWorkstationConfigPollingUntilDone(
    request: CreateWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<WorkstationConfig>.State in
      return try op._extractStatus(WorkstationConfig.self)
    }
    let rawOp = try await self.createWorkstationConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an existing workstation configuration.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstationConfig")
  public func updateWorkstationConfig(
    request: UpdateWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateWorkstationConfig(request: request, options: options)
  }

  /// Updates an existing workstation configuration.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstationConfig")
  public func updateWorkstationConfigPollingUntilDone(
    request: UpdateWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<WorkstationConfig>.State in
      return try op._extractStatus(WorkstationConfig.self)
    }
    let rawOp = try await self.updateWorkstationConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified workstation configuration.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstationConfig")
  public func deleteWorkstationConfig(
    request: DeleteWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteWorkstationConfig(request: request, options: options)
  }

  /// Deletes the specified workstation configuration.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstationConfig")
  public func deleteWorkstationConfigPollingUntilDone(
    request: DeleteWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<WorkstationConfig>.State in
      return try op._extractStatus(WorkstationConfig.self)
    }
    let rawOp = try await self.deleteWorkstationConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Returns the requested workstation.
  ///
  /// @Snippet(path: "Workstations_GetWorkstation")
  public func getWorkstation(
    request: GetWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.Workstation {
    try await self.inner.getWorkstation(request: request, options: options)
  }

  /// Returns all Workstations using the specified workstation configuration.
  ///
  /// @Snippet(path: "Workstations_ListWorkstations")
  public func listWorkstations(
    request: ListWorkstationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationsResponse {
    try await self.inner.listWorkstations(request: request, options: options)
  }

  /// Returns all workstations using the specified workstation configuration
  /// on which the caller has the "workstations.workstations.use" permission.
  ///
  /// @Snippet(path: "Workstations_ListUsableWorkstations")
  public func listUsableWorkstations(
    request: ListUsableWorkstationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse {
    try await self.inner.listUsableWorkstations(request: request, options: options)
  }

  /// Creates a new workstation.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstation")
  public func createWorkstation(
    request: CreateWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createWorkstation(request: request, options: options)
  }

  /// Creates a new workstation.
  ///
  /// @Snippet(path: "Workstations_CreateWorkstation")
  public func createWorkstationPollingUntilDone(
    request: CreateWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Workstation>.State in
      return try op._extractStatus(Workstation.self)
    }
    let rawOp = try await self.createWorkstation(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an existing workstation.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstation")
  public func updateWorkstation(
    request: UpdateWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateWorkstation(request: request, options: options)
  }

  /// Updates an existing workstation.
  ///
  /// @Snippet(path: "Workstations_UpdateWorkstation")
  public func updateWorkstationPollingUntilDone(
    request: UpdateWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Workstation>.State in
      return try op._extractStatus(Workstation.self)
    }
    let rawOp = try await self.updateWorkstation(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified workstation.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstation")
  public func deleteWorkstation(
    request: DeleteWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteWorkstation(request: request, options: options)
  }

  /// Deletes the specified workstation.
  ///
  /// @Snippet(path: "Workstations_DeleteWorkstation")
  public func deleteWorkstationPollingUntilDone(
    request: DeleteWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Workstation>.State in
      return try op._extractStatus(Workstation.self)
    }
    let rawOp = try await self.deleteWorkstation(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Starts running a workstation so that users can connect to it.
  ///
  /// @Snippet(path: "Workstations_StartWorkstation")
  public func startWorkstation(
    request: StartWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.startWorkstation(request: request, options: options)
  }

  /// Starts running a workstation so that users can connect to it.
  ///
  /// @Snippet(path: "Workstations_StartWorkstation")
  public func startWorkstationPollingUntilDone(
    request: StartWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Workstation>.State in
      return try op._extractStatus(Workstation.self)
    }
    let rawOp = try await self.startWorkstation(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Stops running a workstation, reducing costs.
  ///
  /// @Snippet(path: "Workstations_StopWorkstation")
  public func stopWorkstation(
    request: StopWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.stopWorkstation(request: request, options: options)
  }

  /// Stops running a workstation, reducing costs.
  ///
  /// @Snippet(path: "Workstations_StopWorkstation")
  public func stopWorkstationPollingUntilDone(
    request: StopWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Workstation>.State in
      return try op._extractStatus(Workstation.self)
    }
    let rawOp = try await self.stopWorkstation(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Returns a short-lived credential that can be used to send authenticated and
  /// authorized traffic to a workstation.
  /// Once generated this token cannot be revoked and is good for the lifetime
  /// of the token.
  ///
  /// @Snippet(path: "Workstations_GenerateAccessToken")
  public func generateAccessToken(
    request: GenerateAccessTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse {
    try await self.inner.generateAccessToken(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "Workstations_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "Workstations_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "Workstations_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Workstations_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Workstations_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Workstations_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Workstations_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `WorkstationsClient`.
  ///
  /// To mock `WorkstationsClient` change your functions to receive
  /// `some WorkstationsProtocol` or `any WorkstationsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol WorkstationsProtocol: Sendable {
    /// See `WorkstationsClient.getWorkstationCluster`.
    func getWorkstationCluster(
      request: GetWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster

    /// See `WorkstationsClient.listWorkstationClusters`.
    func listWorkstationClusters(
      request: ListWorkstationClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse

    /// See `WorkstationsClient.createWorkstationCluster`.
    func createWorkstationCluster(
      request: CreateWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.createWorkstationCluster`.
    func createWorkstationClusterPollingUntilDone(
      request: CreateWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.updateWorkstationCluster`.
    func updateWorkstationCluster(
      request: UpdateWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.updateWorkstationCluster`.
    func updateWorkstationClusterPollingUntilDone(
      request: UpdateWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.deleteWorkstationCluster`.
    func deleteWorkstationCluster(
      request: DeleteWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.deleteWorkstationCluster`.
    func deleteWorkstationClusterPollingUntilDone(
      request: DeleteWorkstationClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster>

    /// See `WorkstationsClient.getWorkstationConfig`.
    func getWorkstationConfig(
      request: GetWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig

    /// See `WorkstationsClient.listWorkstationConfigs`.
    func listWorkstationConfigs(
      request: ListWorkstationConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse

    /// See `WorkstationsClient.listUsableWorkstationConfigs`.
    func listUsableWorkstationConfigs(
      request: ListUsableWorkstationConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse

    /// See `WorkstationsClient.createWorkstationConfig`.
    func createWorkstationConfig(
      request: CreateWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.createWorkstationConfig`.
    func createWorkstationConfigPollingUntilDone(
      request: CreateWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.updateWorkstationConfig`.
    func updateWorkstationConfig(
      request: UpdateWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.updateWorkstationConfig`.
    func updateWorkstationConfigPollingUntilDone(
      request: UpdateWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.deleteWorkstationConfig`.
    func deleteWorkstationConfig(
      request: DeleteWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.deleteWorkstationConfig`.
    func deleteWorkstationConfigPollingUntilDone(
      request: DeleteWorkstationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig>

    /// See `WorkstationsClient.getWorkstation`.
    func getWorkstation(
      request: GetWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.Workstation

    /// See `WorkstationsClient.listWorkstations`.
    func listWorkstations(
      request: ListWorkstationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationsResponse

    /// See `WorkstationsClient.listUsableWorkstations`.
    func listUsableWorkstations(
      request: ListUsableWorkstationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse

    /// See `WorkstationsClient.createWorkstation`.
    func createWorkstation(
      request: CreateWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.createWorkstation`.
    func createWorkstationPollingUntilDone(
      request: CreateWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.updateWorkstation`.
    func updateWorkstation(
      request: UpdateWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.updateWorkstation`.
    func updateWorkstationPollingUntilDone(
      request: UpdateWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.deleteWorkstation`.
    func deleteWorkstation(
      request: DeleteWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.deleteWorkstation`.
    func deleteWorkstationPollingUntilDone(
      request: DeleteWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.startWorkstation`.
    func startWorkstation(
      request: StartWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.startWorkstation`.
    func startWorkstationPollingUntilDone(
      request: StartWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.stopWorkstation`.
    func stopWorkstation(
      request: StopWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkstationsClient.stopWorkstation`.
    func stopWorkstationPollingUntilDone(
      request: StopWorkstationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Workstation>

    /// See `WorkstationsClient.generateAccessToken`.
    func generateAccessToken(
      request: GenerateAccessTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse

    /// See `WorkstationsClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `WorkstationsClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `WorkstationsClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `WorkstationsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `WorkstationsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `WorkstationsClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.WorkstationsProtocol {
  public func getWorkstationCluster(request: GetWorkstationClusterRequest) async throws
    -> GoogleCloudWorkstationsV1.WorkstationCluster
  {
    try await self.getWorkstationCluster(request: request, options: .init())
  }

  public func getWorkstationCluster(
    request: GetWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getWorkstationCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationCluster {
    let request = GetWorkstationClusterRequest().with {
      $0.name = name
    }
    return try await self.getWorkstationCluster(request: request)
  }

  public func listWorkstationClusters(request: ListWorkstationClustersRequest) async throws
    -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse
  {
    try await self.listWorkstationClusters(request: request, options: .init())
  }

  public func listWorkstationClusters(
    request: ListWorkstationClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listWorkstationClustersByItems(
    request: ListWorkstationClustersRequest
  ) -> some AsyncSequence<WorkstationCluster, Swift.Error> & Sendable {
    self.listWorkstationClustersByItems(request: request, options: .init())
  }

  /// Returns all workstation clusters in the specified location.
  ///
  /// @Snippet(path: "Workstations_ListWorkstationClusters")
  public func listWorkstationClustersByItems(
    request: ListWorkstationClustersRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<WorkstationCluster, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudWorkstationsV1.ListWorkstationClustersResponse in
      var request = request
      request.pageToken = token
      return try await self.listWorkstationClusters(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkstationClustersByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<WorkstationCluster, Swift.Error> & Sendable {
    let request = ListWorkstationClustersRequest().with {
      $0.parent = parent
    }
    return self.listWorkstationClustersByItems(request: request)
  }

  public func createWorkstationCluster(request: CreateWorkstationClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createWorkstationCluster(request: request, options: .init())
  }

  public func createWorkstationCluster(
    request: CreateWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createWorkstationClusterPollingUntilDone(request: CreateWorkstationClusterRequest)
    async throws -> any GoogleGax.PollableOperation<WorkstationCluster>
  {
    try await self.createWorkstationClusterPollingUntilDone(request: request, options: .init())
  }

  public func createWorkstationClusterPollingUntilDone(
    request: CreateWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationCluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createWorkstationClusterPollingUntilDone(
    parent: Swift.String,
    workstationCluster: WorkstationCluster?,
    workstationClusterId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster> {
    let request = CreateWorkstationClusterRequest().with {
      $0.parent = parent
      $0.workstationCluster = workstationCluster
      $0.workstationClusterId = workstationClusterId
    }
    return try await self.createWorkstationClusterPollingUntilDone(request: request)
  }

  public func updateWorkstationCluster(request: UpdateWorkstationClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateWorkstationCluster(request: request, options: .init())
  }

  public func updateWorkstationCluster(
    request: UpdateWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateWorkstationClusterPollingUntilDone(request: UpdateWorkstationClusterRequest)
    async throws -> any GoogleGax.PollableOperation<WorkstationCluster>
  {
    try await self.updateWorkstationClusterPollingUntilDone(request: request, options: .init())
  }

  public func updateWorkstationClusterPollingUntilDone(
    request: UpdateWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationCluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkstationClusterPollingUntilDone(
    workstationCluster: WorkstationCluster?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster> {
    let request = UpdateWorkstationClusterRequest().with {
      $0.workstationCluster = workstationCluster
      $0.updateMask = updateMask
    }
    return try await self.updateWorkstationClusterPollingUntilDone(request: request)
  }

  public func deleteWorkstationCluster(request: DeleteWorkstationClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteWorkstationCluster(request: request, options: .init())
  }

  public func deleteWorkstationCluster(
    request: DeleteWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteWorkstationClusterPollingUntilDone(request: DeleteWorkstationClusterRequest)
    async throws -> any GoogleGax.PollableOperation<WorkstationCluster>
  {
    try await self.deleteWorkstationClusterPollingUntilDone(request: request, options: .init())
  }

  public func deleteWorkstationClusterPollingUntilDone(
    request: DeleteWorkstationClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationCluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkstationClusterPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<WorkstationCluster> {
    let request = DeleteWorkstationClusterRequest().with {
      $0.name = name
    }
    return try await self.deleteWorkstationClusterPollingUntilDone(request: request)
  }

  public func getWorkstationConfig(request: GetWorkstationConfigRequest) async throws
    -> GoogleCloudWorkstationsV1.WorkstationConfig
  {
    try await self.getWorkstationConfig(request: request, options: .init())
  }

  public func getWorkstationConfig(
    request: GetWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getWorkstationConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkstationsV1.WorkstationConfig {
    let request = GetWorkstationConfigRequest().with {
      $0.name = name
    }
    return try await self.getWorkstationConfig(request: request)
  }

  public func listWorkstationConfigs(request: ListWorkstationConfigsRequest) async throws
    -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse
  {
    try await self.listWorkstationConfigs(request: request, options: .init())
  }

  public func listWorkstationConfigs(
    request: ListWorkstationConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listWorkstationConfigsByItems(
    request: ListWorkstationConfigsRequest
  ) -> some AsyncSequence<WorkstationConfig, Swift.Error> & Sendable {
    self.listWorkstationConfigsByItems(request: request, options: .init())
  }

  /// Returns all workstation configurations in the specified cluster.
  ///
  /// @Snippet(path: "Workstations_ListWorkstationConfigs")
  public func listWorkstationConfigsByItems(
    request: ListWorkstationConfigsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<WorkstationConfig, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudWorkstationsV1.ListWorkstationConfigsResponse in
      var request = request
      request.pageToken = token
      return try await self.listWorkstationConfigs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkstationConfigsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<WorkstationConfig, Swift.Error> & Sendable {
    let request = ListWorkstationConfigsRequest().with {
      $0.parent = parent
    }
    return self.listWorkstationConfigsByItems(request: request)
  }

  public func listUsableWorkstationConfigs(request: ListUsableWorkstationConfigsRequest)
    async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse
  {
    try await self.listUsableWorkstationConfigs(request: request, options: .init())
  }

  public func listUsableWorkstationConfigs(
    request: ListUsableWorkstationConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listUsableWorkstationConfigsByItems(
    request: ListUsableWorkstationConfigsRequest
  ) -> some AsyncSequence<WorkstationConfig, Swift.Error> & Sendable {
    self.listUsableWorkstationConfigsByItems(request: request, options: .init())
  }

  /// Returns all workstation configurations in the specified cluster on which
  /// the caller has the "workstations.workstation.create" permission.
  ///
  /// @Snippet(path: "Workstations_ListUsableWorkstationConfigs")
  public func listUsableWorkstationConfigsByItems(
    request: ListUsableWorkstationConfigsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<WorkstationConfig, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudWorkstationsV1.ListUsableWorkstationConfigsResponse in
      var request = request
      request.pageToken = token
      return try await self.listUsableWorkstationConfigs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listUsableWorkstationConfigsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<WorkstationConfig, Swift.Error> & Sendable {
    let request = ListUsableWorkstationConfigsRequest().with {
      $0.parent = parent
    }
    return self.listUsableWorkstationConfigsByItems(request: request)
  }

  public func createWorkstationConfig(request: CreateWorkstationConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createWorkstationConfig(request: request, options: .init())
  }

  public func createWorkstationConfig(
    request: CreateWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createWorkstationConfigPollingUntilDone(request: CreateWorkstationConfigRequest)
    async throws -> any GoogleGax.PollableOperation<WorkstationConfig>
  {
    try await self.createWorkstationConfigPollingUntilDone(request: request, options: .init())
  }

  public func createWorkstationConfigPollingUntilDone(
    request: CreateWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationConfig>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createWorkstationConfigPollingUntilDone(
    parent: Swift.String,
    workstationConfig: WorkstationConfig?,
    workstationConfigId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig> {
    let request = CreateWorkstationConfigRequest().with {
      $0.parent = parent
      $0.workstationConfig = workstationConfig
      $0.workstationConfigId = workstationConfigId
    }
    return try await self.createWorkstationConfigPollingUntilDone(request: request)
  }

  public func updateWorkstationConfig(request: UpdateWorkstationConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateWorkstationConfig(request: request, options: .init())
  }

  public func updateWorkstationConfig(
    request: UpdateWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateWorkstationConfigPollingUntilDone(request: UpdateWorkstationConfigRequest)
    async throws -> any GoogleGax.PollableOperation<WorkstationConfig>
  {
    try await self.updateWorkstationConfigPollingUntilDone(request: request, options: .init())
  }

  public func updateWorkstationConfigPollingUntilDone(
    request: UpdateWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationConfig>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkstationConfigPollingUntilDone(
    workstationConfig: WorkstationConfig?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig> {
    let request = UpdateWorkstationConfigRequest().with {
      $0.workstationConfig = workstationConfig
      $0.updateMask = updateMask
    }
    return try await self.updateWorkstationConfigPollingUntilDone(request: request)
  }

  public func deleteWorkstationConfig(request: DeleteWorkstationConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteWorkstationConfig(request: request, options: .init())
  }

  public func deleteWorkstationConfig(
    request: DeleteWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteWorkstationConfigPollingUntilDone(request: DeleteWorkstationConfigRequest)
    async throws -> any GoogleGax.PollableOperation<WorkstationConfig>
  {
    try await self.deleteWorkstationConfigPollingUntilDone(request: request, options: .init())
  }

  public func deleteWorkstationConfigPollingUntilDone(
    request: DeleteWorkstationConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<WorkstationConfig>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkstationConfigPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<WorkstationConfig> {
    let request = DeleteWorkstationConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteWorkstationConfigPollingUntilDone(request: request)
  }

  public func getWorkstation(request: GetWorkstationRequest) async throws
    -> GoogleCloudWorkstationsV1.Workstation
  {
    try await self.getWorkstation(request: request, options: .init())
  }

  public func getWorkstation(
    request: GetWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.Workstation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getWorkstation(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkstationsV1.Workstation {
    let request = GetWorkstationRequest().with {
      $0.name = name
    }
    return try await self.getWorkstation(request: request)
  }

  public func listWorkstations(request: ListWorkstationsRequest) async throws
    -> GoogleCloudWorkstationsV1.ListWorkstationsResponse
  {
    try await self.listWorkstations(request: request, options: .init())
  }

  public func listWorkstations(
    request: ListWorkstationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListWorkstationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listWorkstationsByItems(
    request: ListWorkstationsRequest
  ) -> some AsyncSequence<Workstation, Swift.Error> & Sendable {
    self.listWorkstationsByItems(request: request, options: .init())
  }

  /// Returns all Workstations using the specified workstation configuration.
  ///
  /// @Snippet(path: "Workstations_ListWorkstations")
  public func listWorkstationsByItems(
    request: ListWorkstationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Workstation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudWorkstationsV1.ListWorkstationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listWorkstations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkstationsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Workstation, Swift.Error> & Sendable {
    let request = ListWorkstationsRequest().with {
      $0.parent = parent
    }
    return self.listWorkstationsByItems(request: request)
  }

  public func listUsableWorkstations(request: ListUsableWorkstationsRequest) async throws
    -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse
  {
    try await self.listUsableWorkstations(request: request, options: .init())
  }

  public func listUsableWorkstations(
    request: ListUsableWorkstationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listUsableWorkstationsByItems(
    request: ListUsableWorkstationsRequest
  ) -> some AsyncSequence<Workstation, Swift.Error> & Sendable {
    self.listUsableWorkstationsByItems(request: request, options: .init())
  }

  /// Returns all workstations using the specified workstation configuration
  /// on which the caller has the "workstations.workstations.use" permission.
  ///
  /// @Snippet(path: "Workstations_ListUsableWorkstations")
  public func listUsableWorkstationsByItems(
    request: ListUsableWorkstationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Workstation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudWorkstationsV1.ListUsableWorkstationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listUsableWorkstations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listUsableWorkstationsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Workstation, Swift.Error> & Sendable {
    let request = ListUsableWorkstationsRequest().with {
      $0.parent = parent
    }
    return self.listUsableWorkstationsByItems(request: request)
  }

  public func createWorkstation(request: CreateWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createWorkstation(request: request, options: .init())
  }

  public func createWorkstation(
    request: CreateWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createWorkstationPollingUntilDone(request: CreateWorkstationRequest) async throws
    -> any GoogleGax.PollableOperation<Workstation>
  {
    try await self.createWorkstationPollingUntilDone(request: request, options: .init())
  }

  public func createWorkstationPollingUntilDone(
    request: CreateWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createWorkstationPollingUntilDone(
    parent: Swift.String,
    workstation: Workstation?,
    workstationId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let request = CreateWorkstationRequest().with {
      $0.parent = parent
      $0.workstation = workstation
      $0.workstationId = workstationId
    }
    return try await self.createWorkstationPollingUntilDone(request: request)
  }

  public func updateWorkstation(request: UpdateWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateWorkstation(request: request, options: .init())
  }

  public func updateWorkstation(
    request: UpdateWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateWorkstationPollingUntilDone(request: UpdateWorkstationRequest) async throws
    -> any GoogleGax.PollableOperation<Workstation>
  {
    try await self.updateWorkstationPollingUntilDone(request: request, options: .init())
  }

  public func updateWorkstationPollingUntilDone(
    request: UpdateWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkstationPollingUntilDone(
    workstation: Workstation?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let request = UpdateWorkstationRequest().with {
      $0.workstation = workstation
      $0.updateMask = updateMask
    }
    return try await self.updateWorkstationPollingUntilDone(request: request)
  }

  public func deleteWorkstation(request: DeleteWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteWorkstation(request: request, options: .init())
  }

  public func deleteWorkstation(
    request: DeleteWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteWorkstationPollingUntilDone(request: DeleteWorkstationRequest) async throws
    -> any GoogleGax.PollableOperation<Workstation>
  {
    try await self.deleteWorkstationPollingUntilDone(request: request, options: .init())
  }

  public func deleteWorkstationPollingUntilDone(
    request: DeleteWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkstationPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let request = DeleteWorkstationRequest().with {
      $0.name = name
    }
    return try await self.deleteWorkstationPollingUntilDone(request: request)
  }

  public func startWorkstation(request: StartWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.startWorkstation(request: request, options: .init())
  }

  public func startWorkstation(
    request: StartWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func startWorkstationPollingUntilDone(request: StartWorkstationRequest) async throws
    -> any GoogleGax.PollableOperation<Workstation>
  {
    try await self.startWorkstationPollingUntilDone(request: request, options: .init())
  }

  public func startWorkstationPollingUntilDone(
    request: StartWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func startWorkstationPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let request = StartWorkstationRequest().with {
      $0.name = name
    }
    return try await self.startWorkstationPollingUntilDone(request: request)
  }

  public func stopWorkstation(request: StopWorkstationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.stopWorkstation(request: request, options: .init())
  }

  public func stopWorkstation(
    request: StopWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func stopWorkstationPollingUntilDone(request: StopWorkstationRequest) async throws
    -> any GoogleGax.PollableOperation<Workstation>
  {
    try await self.stopWorkstationPollingUntilDone(request: request, options: .init())
  }

  public func stopWorkstationPollingUntilDone(
    request: StopWorkstationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Workstation>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func stopWorkstationPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Workstation> {
    let request = StopWorkstationRequest().with {
      $0.name = name
    }
    return try await self.stopWorkstationPollingUntilDone(request: request)
  }

  public func generateAccessToken(request: GenerateAccessTokenRequest) async throws
    -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse
  {
    try await self.generateAccessToken(request: request, options: .init())
  }

  public func generateAccessToken(
    request: GenerateAccessTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func generateAccessToken(
    workstation: Swift.String,
  ) async throws -> GoogleCloudWorkstationsV1.GenerateAccessTokenResponse {
    let request = GenerateAccessTokenRequest().with {
      $0.workstation = workstation
    }
    return try await self.generateAccessToken(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Workstations_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
